// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: adminusers.sql

package sqlcgen

import (
	"context"
)

const createAdminUser = `-- name: CreateAdminUser :exec
INSERT INTO admin_users (id, store_id, name, email, password_hash, role, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAdminUserParams struct {
	ID           string           `json:"id"`
	StoreID      string           `json:"storeId"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"passwordHash"`
	Role         AdminUsersRole   `json:"role"`
	Status       AdminUsersStatus `json:"status"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error {
	_, err := q.db.ExecContext(ctx, createAdminUser,
		arg.ID,
		arg.StoreID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
	)
	return err
}

const deleteAdminUser = `-- name: DeleteAdminUser :exec
DELETE FROM admin_users WHERE id = ? AND store_id = ?
`

type DeleteAdminUserParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) DeleteAdminUser(ctx context.Context, arg DeleteAdminUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteAdminUser, arg.ID, arg.StoreID)
	return err
}

const getAdminUserScoped = `-- name: GetAdminUserScoped :one
SELECT id, store_id, name, email, password_hash, role, status, last_active_at, created_at, updated_at FROM admin_users WHERE id = ? AND store_id = ? LIMIT 1
`

type GetAdminUserScopedParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) GetAdminUserScoped(ctx context.Context, arg GetAdminUserScopedParams) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserScoped, arg.ID, arg.StoreID)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, store_id, name, email, password_hash, role, status, last_active_at, created_at, updated_at FROM admin_users WHERE store_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAdminUsers(ctx context.Context, storeID string) ([]AdminUser, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUser{}
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminUser = `-- name: UpdateAdminUser :exec
UPDATE admin_users SET name = ?, email = ?, role = ?, status = ?
WHERE id = ? AND store_id = ?
`

type UpdateAdminUserParams struct {
	Name    string           `json:"name"`
	Email   string           `json:"email"`
	Role    AdminUsersRole   `json:"role"`
	Status  AdminUsersStatus `json:"status"`
	ID      string           `json:"id"`
	StoreID string           `json:"storeId"`
}

func (q *Queries) UpdateAdminUser(ctx context.Context, arg UpdateAdminUserParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminUser,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Status,
		arg.ID,
		arg.StoreID,
	)
	return err
}

const updateAdminUserPassword = `-- name: UpdateAdminUserPassword :exec
UPDATE admin_users SET password_hash = ? WHERE id = ? AND store_id = ?
`

type UpdateAdminUserPasswordParams struct {
	PasswordHash string `json:"passwordHash"`
	ID           string `json:"id"`
	StoreID      string `json:"storeId"`
}

func (q *Queries) UpdateAdminUserPassword(ctx context.Context, arg UpdateAdminUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminUserPassword, arg.PasswordHash, arg.ID, arg.StoreID)
	return err
}
