// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, actor, subject_id, token_hash, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateRefreshTokenParams struct {
	ID        string             `json:"id"`
	Actor     RefreshTokensActor `json:"actor"`
	SubjectID string             `json:"subjectId"`
	TokenHash string             `json:"tokenHash"`
	ExpiresAt time.Time          `json:"expiresAt"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.Actor,
		arg.SubjectID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getAdminUserByEmail = `-- name: GetAdminUserByEmail :one
SELECT id, store_id, name, email, password_hash, role, status, last_active_at, created_at, updated_at, username FROM admin_users WHERE email = ? LIMIT 1
`

func (q *Queries) GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const getAdminUserByEmailOrUsername = `-- name: GetAdminUserByEmailOrUsername :one
SELECT id, store_id, name, email, password_hash, role, status, last_active_at, created_at, updated_at, username FROM admin_users WHERE email = ? OR username = ? LIMIT 1
`

type GetAdminUserByEmailOrUsernameParams struct {
	Email    string         `json:"email"`
	Username sql.NullString `json:"username"`
}

func (q *Queries) GetAdminUserByEmailOrUsername(ctx context.Context, arg GetAdminUserByEmailOrUsernameParams) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByEmailOrUsername, arg.Email, arg.Username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT id, store_id, name, email, password_hash, role, status, last_active_at, created_at, updated_at, username FROM admin_users WHERE id = ? LIMIT 1
`

func (q *Queries) GetAdminUserByID(ctx context.Context, id string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const getFirstStore = `-- name: GetFirstStore :one
SELECT id, name, type, address, phone, timezone, currency, created_at, updated_at, logo_url, status, slug FROM stores ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetFirstStore(ctx context.Context) (Store, error) {
	row := q.db.QueryRowContext(ctx, getFirstStore)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Address,
		&i.Phone,
		&i.Timezone,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
		&i.Status,
		&i.Slug,
	)
	return i, err
}

const getPlatformUserByEmail = `-- name: GetPlatformUserByEmail :one
SELECT id, name, email, password_hash, status, created_at, updated_at FROM platform_users WHERE email = ? LIMIT 1
`

func (q *Queries) GetPlatformUserByEmail(ctx context.Context, email string) (PlatformUser, error) {
	row := q.db.QueryRowContext(ctx, getPlatformUserByEmail, email)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformUserByID = `-- name: GetPlatformUserByID :one
SELECT id, name, email, password_hash, status, created_at, updated_at FROM platform_users WHERE id = ? LIMIT 1
`

func (q *Queries) GetPlatformUserByID(ctx context.Context, id string) (PlatformUser, error) {
	row := q.db.QueryRowContext(ctx, getPlatformUserByID, id)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, subject_id, token_hash, expires_at, revoked_at, created_at, actor FROM refresh_tokens WHERE token_hash = ? LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Actor,
	)
	return i, err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, store_id, name, username, email, password_hash, role, status, created_at, updated_at, pin_hash FROM staff WHERE id = ? LIMIT 1
`

func (q *Queries) GetStaffByID(ctx context.Context, id string) (Staff, error) {
	row := q.db.QueryRowContext(ctx, getStaffByID, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PinHash,
	)
	return i, err
}

const getStaffByUsername = `-- name: GetStaffByUsername :one
SELECT id, store_id, name, username, email, password_hash, role, status, created_at, updated_at, pin_hash FROM staff WHERE username = ? LIMIT 1
`

func (q *Queries) GetStaffByUsername(ctx context.Context, username string) (Staff, error) {
	row := q.db.QueryRowContext(ctx, getStaffByUsername, username)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PinHash,
	)
	return i, err
}

const getStoreStatus = `-- name: GetStoreStatus :one
SELECT status FROM stores WHERE id = ? LIMIT 1
`

// Bacaan langsung ke `stores.status` — pengecualian shared-kernel yang sama classnya dengan
// kolom profil milik `settings` (lihat MODULE_MAP.md); dipakai utk gerbang suspensi tenant
// (PLAN.md §2.13), bukan kepemilikan tabel oleh `auth`.
func (q *Queries) GetStoreStatus(ctx context.Context, id string) (StoresStatus, error) {
	row := q.db.QueryRowContext(ctx, getStoreStatus, id)
	var status StoresStatus
	err := row.Scan(&status)
	return status, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = ? WHERE token_hash = ? AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	RevokedAt sql.NullTime `json:"revokedAt"`
	TokenHash string       `json:"tokenHash"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.RevokedAt, arg.TokenHash)
	return err
}

const touchAdminUserLastActive = `-- name: TouchAdminUserLastActive :exec
UPDATE admin_users SET last_active_at = ? WHERE id = ?
`

type TouchAdminUserLastActiveParams struct {
	LastActiveAt sql.NullTime `json:"lastActiveAt"`
	ID           string       `json:"id"`
}

func (q *Queries) TouchAdminUserLastActive(ctx context.Context, arg TouchAdminUserLastActiveParams) error {
	_, err := q.db.ExecContext(ctx, touchAdminUserLastActive, arg.LastActiveAt, arg.ID)
	return err
}
