// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cashmovements.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countCashMovements = `-- name: CountCashMovements :one
SELECT COUNT(*) FROM cash_movements WHERE store_id = ?
`

func (q *Queries) CountCashMovements(ctx context.Context, storeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCashMovements, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCashMovement = `-- name: CreateCashMovement :exec
INSERT INTO cash_movements (id, store_id, shift_id, type, amount, notes, created_by, approved_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCashMovementParams struct {
	ID         string            `json:"id"`
	StoreID    string            `json:"storeId"`
	ShiftID    sql.NullString    `json:"shiftId"`
	Type       CashMovementsType `json:"type"`
	Amount     int64             `json:"amount"`
	Notes      sql.NullString    `json:"notes"`
	CreatedBy  sql.NullString    `json:"createdBy"`
	ApprovedBy sql.NullString    `json:"approvedBy"`
}

func (q *Queries) CreateCashMovement(ctx context.Context, arg CreateCashMovementParams) error {
	_, err := q.db.ExecContext(ctx, createCashMovement,
		arg.ID,
		arg.StoreID,
		arg.ShiftID,
		arg.Type,
		arg.Amount,
		arg.Notes,
		arg.CreatedBy,
		arg.ApprovedBy,
	)
	return err
}

const getCashMovement = `-- name: GetCashMovement :one
SELECT id, store_id, shift_id, type, amount, notes, created_by, approved_by, created_at FROM cash_movements WHERE id = ? AND store_id = ? LIMIT 1
`

type GetCashMovementParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) GetCashMovement(ctx context.Context, arg GetCashMovementParams) (CashMovement, error) {
	row := q.db.QueryRowContext(ctx, getCashMovement, arg.ID, arg.StoreID)
	var i CashMovement
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ShiftID,
		&i.Type,
		&i.Amount,
		&i.Notes,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listCashMovements = `-- name: ListCashMovements :many
SELECT id, store_id, shift_id, type, amount, notes, created_by, approved_by, created_at FROM cash_movements WHERE store_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListCashMovementsParams struct {
	StoreID string `json:"storeId"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListCashMovements(ctx context.Context, arg ListCashMovementsParams) ([]CashMovement, error) {
	rows, err := q.db.QueryContext(ctx, listCashMovements, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashMovement{}
	for rows.Next() {
		var i CashMovement
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ShiftID,
			&i.Type,
			&i.Amount,
			&i.Notes,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
