// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: categories.sql

package sqlcgen

import (
	"context"
	"time"
)

const createCategory = `-- name: CreateCategory :exec
INSERT INTO product_categories (id, store_id, name, sort_order) VALUES (?, ?, ?, ?)
`

type CreateCategoryParams struct {
	ID        string `json:"id"`
	StoreID   string `json:"storeId"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sortOrder"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.StoreID,
		arg.Name,
		arg.SortOrder,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM product_categories WHERE id = ? AND store_id = ?
`

type DeleteCategoryParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, arg.ID, arg.StoreID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, store_id, name, sort_order, created_at, updated_at FROM product_categories WHERE id = ? AND store_id = ? LIMIT 1
`

type GetCategoryParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRowContext(ctx, getCategory, arg.ID, arg.StoreID)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT c.id, c.store_id, c.name, c.sort_order, c.created_at, c.updated_at, (SELECT COUNT(*) FROM products p WHERE p.category_id = c.id) AS product_count
FROM product_categories c
WHERE c.store_id = ?
ORDER BY c.sort_order ASC, c.name ASC
`

type ListCategoriesRow struct {
	ID           string    `json:"id"`
	StoreID      string    `json:"storeId"`
	Name         string    `json:"name"`
	SortOrder    int32     `json:"sortOrder"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	ProductCount int64     `json:"productCount"`
}

func (q *Queries) ListCategories(ctx context.Context, storeID string) ([]ListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE product_categories SET name = ?, sort_order = ? WHERE id = ? AND store_id = ?
`

type UpdateCategoryParams struct {
	Name      string `json:"name"`
	SortOrder int32  `json:"sortOrder"`
	ID        string `json:"id"`
	StoreID   string `json:"storeId"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.SortOrder,
		arg.ID,
		arg.StoreID,
	)
	return err
}
