// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AdminUsersRole string

const (
	AdminUsersRoleOwner   AdminUsersRole = "owner"
	AdminUsersRoleAdmin   AdminUsersRole = "admin"
	AdminUsersRoleManager AdminUsersRole = "manager"
	AdminUsersRoleViewer  AdminUsersRole = "viewer"
)

func (e *AdminUsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminUsersRole(s)
	case string:
		*e = AdminUsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminUsersRole: %T", src)
	}
	return nil
}

type NullAdminUsersRole struct {
	AdminUsersRole AdminUsersRole `json:"adminUsersRole"`
	Valid          bool           `json:"valid"` // Valid is true if AdminUsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.AdminUsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminUsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminUsersRole), nil
}

type AdminUsersStatus string

const (
	AdminUsersStatusActive   AdminUsersStatus = "active"
	AdminUsersStatusInactive AdminUsersStatus = "inactive"
)

func (e *AdminUsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminUsersStatus(s)
	case string:
		*e = AdminUsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminUsersStatus: %T", src)
	}
	return nil
}

type NullAdminUsersStatus struct {
	AdminUsersStatus AdminUsersStatus `json:"adminUsersStatus"`
	Valid            bool             `json:"valid"` // Valid is true if AdminUsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AdminUsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminUsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminUsersStatus), nil
}

type CashMovementsType string

const (
	CashMovementsTypeCapital    CashMovementsType = "capital"
	CashMovementsTypeExpense    CashMovementsType = "expense"
	CashMovementsTypeAdjustment CashMovementsType = "adjustment"
)

func (e *CashMovementsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CashMovementsType(s)
	case string:
		*e = CashMovementsType(s)
	default:
		return fmt.Errorf("unsupported scan type for CashMovementsType: %T", src)
	}
	return nil
}

type NullCashMovementsType struct {
	CashMovementsType CashMovementsType `json:"cashMovementsType"`
	Valid             bool              `json:"valid"` // Valid is true if CashMovementsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCashMovementsType) Scan(value interface{}) error {
	if value == nil {
		ns.CashMovementsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CashMovementsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCashMovementsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CashMovementsType), nil
}

type DiningTablesStatus string

const (
	DiningTablesStatusActive   DiningTablesStatus = "active"
	DiningTablesStatusInactive DiningTablesStatus = "inactive"
)

func (e *DiningTablesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiningTablesStatus(s)
	case string:
		*e = DiningTablesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DiningTablesStatus: %T", src)
	}
	return nil
}

type NullDiningTablesStatus struct {
	DiningTablesStatus DiningTablesStatus `json:"diningTablesStatus"`
	Valid              bool               `json:"valid"` // Valid is true if DiningTablesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiningTablesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DiningTablesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiningTablesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiningTablesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiningTablesStatus), nil
}

type PaymentsMethod string

const (
	PaymentsMethodQris PaymentsMethod = "qris"
)

func (e *PaymentsMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentsMethod(s)
	case string:
		*e = PaymentsMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentsMethod: %T", src)
	}
	return nil
}

type NullPaymentsMethod struct {
	PaymentsMethod PaymentsMethod `json:"paymentsMethod"`
	Valid          bool           `json:"valid"` // Valid is true if PaymentsMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentsMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentsMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentsMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentsMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentsMethod), nil
}

type PaymentsProvider string

const (
	PaymentsProviderXendit PaymentsProvider = "xendit"
)

func (e *PaymentsProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentsProvider(s)
	case string:
		*e = PaymentsProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentsProvider: %T", src)
	}
	return nil
}

type NullPaymentsProvider struct {
	PaymentsProvider PaymentsProvider `json:"paymentsProvider"`
	Valid            bool             `json:"valid"` // Valid is true if PaymentsProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentsProvider) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentsProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentsProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentsProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentsProvider), nil
}

type PaymentsStatus string

const (
	PaymentsStatusPending PaymentsStatus = "pending"
	PaymentsStatusPaid    PaymentsStatus = "paid"
	PaymentsStatusExpired PaymentsStatus = "expired"
	PaymentsStatusFailed  PaymentsStatus = "failed"
)

func (e *PaymentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentsStatus(s)
	case string:
		*e = PaymentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentsStatus: %T", src)
	}
	return nil
}

type NullPaymentsStatus struct {
	PaymentsStatus PaymentsStatus `json:"paymentsStatus"`
	Valid          bool           `json:"valid"` // Valid is true if PaymentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentsStatus), nil
}

type ProductsStatus string

const (
	ProductsStatusActive   ProductsStatus = "active"
	ProductsStatusInactive ProductsStatus = "inactive"
)

func (e *ProductsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductsStatus(s)
	case string:
		*e = ProductsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductsStatus: %T", src)
	}
	return nil
}

type NullProductsStatus struct {
	ProductsStatus ProductsStatus `json:"productsStatus"`
	Valid          bool           `json:"valid"` // Valid is true if ProductsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductsStatus), nil
}

type RefreshTokensActor string

const (
	RefreshTokensActorAdmin RefreshTokensActor = "admin"
	RefreshTokensActorStaff RefreshTokensActor = "staff"
)

func (e *RefreshTokensActor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RefreshTokensActor(s)
	case string:
		*e = RefreshTokensActor(s)
	default:
		return fmt.Errorf("unsupported scan type for RefreshTokensActor: %T", src)
	}
	return nil
}

type NullRefreshTokensActor struct {
	RefreshTokensActor RefreshTokensActor `json:"refreshTokensActor"`
	Valid              bool               `json:"valid"` // Valid is true if RefreshTokensActor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRefreshTokensActor) Scan(value interface{}) error {
	if value == nil {
		ns.RefreshTokensActor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RefreshTokensActor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRefreshTokensActor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RefreshTokensActor), nil
}

type SelfOrdersPaymentMethod string

const (
	SelfOrdersPaymentMethodQris SelfOrdersPaymentMethod = "qris"
	SelfOrdersPaymentMethodCash SelfOrdersPaymentMethod = "cash"
)

func (e *SelfOrdersPaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SelfOrdersPaymentMethod(s)
	case string:
		*e = SelfOrdersPaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for SelfOrdersPaymentMethod: %T", src)
	}
	return nil
}

type NullSelfOrdersPaymentMethod struct {
	SelfOrdersPaymentMethod SelfOrdersPaymentMethod `json:"selfOrdersPaymentMethod"`
	Valid                   bool                    `json:"valid"` // Valid is true if SelfOrdersPaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSelfOrdersPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.SelfOrdersPaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SelfOrdersPaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSelfOrdersPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SelfOrdersPaymentMethod), nil
}

type SelfOrdersPaymentStatus string

const (
	SelfOrdersPaymentStatusPending SelfOrdersPaymentStatus = "pending"
	SelfOrdersPaymentStatusPaid    SelfOrdersPaymentStatus = "paid"
	SelfOrdersPaymentStatusExpired SelfOrdersPaymentStatus = "expired"
	SelfOrdersPaymentStatusFailed  SelfOrdersPaymentStatus = "failed"
	SelfOrdersPaymentStatusUnpaid  SelfOrdersPaymentStatus = "unpaid"
)

func (e *SelfOrdersPaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SelfOrdersPaymentStatus(s)
	case string:
		*e = SelfOrdersPaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SelfOrdersPaymentStatus: %T", src)
	}
	return nil
}

type NullSelfOrdersPaymentStatus struct {
	SelfOrdersPaymentStatus SelfOrdersPaymentStatus `json:"selfOrdersPaymentStatus"`
	Valid                   bool                    `json:"valid"` // Valid is true if SelfOrdersPaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSelfOrdersPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SelfOrdersPaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SelfOrdersPaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSelfOrdersPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SelfOrdersPaymentStatus), nil
}

type SelfOrdersStatus string

const (
	SelfOrdersStatusPlaced    SelfOrdersStatus = "placed"
	SelfOrdersStatusPreparing SelfOrdersStatus = "preparing"
	SelfOrdersStatusCompleted SelfOrdersStatus = "completed"
)

func (e *SelfOrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SelfOrdersStatus(s)
	case string:
		*e = SelfOrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SelfOrdersStatus: %T", src)
	}
	return nil
}

type NullSelfOrdersStatus struct {
	SelfOrdersStatus SelfOrdersStatus `json:"selfOrdersStatus"`
	Valid            bool             `json:"valid"` // Valid is true if SelfOrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSelfOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SelfOrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SelfOrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSelfOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SelfOrdersStatus), nil
}

type ShiftsStatus string

const (
	ShiftsStatusOpen   ShiftsStatus = "open"
	ShiftsStatusClosed ShiftsStatus = "closed"
)

func (e *ShiftsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShiftsStatus(s)
	case string:
		*e = ShiftsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShiftsStatus: %T", src)
	}
	return nil
}

type NullShiftsStatus struct {
	ShiftsStatus ShiftsStatus `json:"shiftsStatus"`
	Valid        bool         `json:"valid"` // Valid is true if ShiftsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShiftsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShiftsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShiftsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShiftsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShiftsStatus), nil
}

type StaffRole string

const (
	StaffRoleCashier    StaffRole = "cashier"
	StaffRoleSupervisor StaffRole = "supervisor"
)

func (e *StaffRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StaffRole(s)
	case string:
		*e = StaffRole(s)
	default:
		return fmt.Errorf("unsupported scan type for StaffRole: %T", src)
	}
	return nil
}

type NullStaffRole struct {
	StaffRole StaffRole `json:"staffRole"`
	Valid     bool      `json:"valid"` // Valid is true if StaffRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStaffRole) Scan(value interface{}) error {
	if value == nil {
		ns.StaffRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StaffRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStaffRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StaffRole), nil
}

type StaffStatus string

const (
	StaffStatusActive   StaffStatus = "active"
	StaffStatusInactive StaffStatus = "inactive"
)

func (e *StaffStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StaffStatus(s)
	case string:
		*e = StaffStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StaffStatus: %T", src)
	}
	return nil
}

type NullStaffStatus struct {
	StaffStatus StaffStatus `json:"staffStatus"`
	Valid       bool        `json:"valid"` // Valid is true if StaffStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStaffStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StaffStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StaffStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStaffStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StaffStatus), nil
}

type TransactionsOrderType string

const (
	TransactionsOrderTypeDineIn   TransactionsOrderType = "dineIn"
	TransactionsOrderTypeTakeaway TransactionsOrderType = "takeaway"
)

func (e *TransactionsOrderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsOrderType(s)
	case string:
		*e = TransactionsOrderType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsOrderType: %T", src)
	}
	return nil
}

type NullTransactionsOrderType struct {
	TransactionsOrderType TransactionsOrderType `json:"transactionsOrderType"`
	Valid                 bool                  `json:"valid"` // Valid is true if TransactionsOrderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionsOrderType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionsOrderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionsOrderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionsOrderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionsOrderType), nil
}

type TransactionsPaymentMethod string

const (
	TransactionsPaymentMethodCash TransactionsPaymentMethod = "cash"
	TransactionsPaymentMethodQris TransactionsPaymentMethod = "qris"
)

func (e *TransactionsPaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsPaymentMethod(s)
	case string:
		*e = TransactionsPaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsPaymentMethod: %T", src)
	}
	return nil
}

type NullTransactionsPaymentMethod struct {
	TransactionsPaymentMethod TransactionsPaymentMethod `json:"transactionsPaymentMethod"`
	Valid                     bool                      `json:"valid"` // Valid is true if TransactionsPaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionsPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionsPaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionsPaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionsPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionsPaymentMethod), nil
}

type TransactionsSource string

const (
	TransactionsSourceCashier   TransactionsSource = "cashier"
	TransactionsSourceSelfOrder TransactionsSource = "self_order"
)

func (e *TransactionsSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsSource(s)
	case string:
		*e = TransactionsSource(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsSource: %T", src)
	}
	return nil
}

type NullTransactionsSource struct {
	TransactionsSource TransactionsSource `json:"transactionsSource"`
	Valid              bool               `json:"valid"` // Valid is true if TransactionsSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionsSource) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionsSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionsSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionsSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionsSource), nil
}

type TransactionsStatus string

const (
	TransactionsStatusCompleted TransactionsStatus = "completed"
	TransactionsStatusVoided    TransactionsStatus = "voided"
	TransactionsStatusRefunded  TransactionsStatus = "refunded"
)

func (e *TransactionsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsStatus(s)
	case string:
		*e = TransactionsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsStatus: %T", src)
	}
	return nil
}

type NullTransactionsStatus struct {
	TransactionsStatus TransactionsStatus `json:"transactionsStatus"`
	Valid              bool               `json:"valid"` // Valid is true if TransactionsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionsStatus), nil
}

type WithdrawalsStatus string

const (
	WithdrawalsStatusPending    WithdrawalsStatus = "pending"
	WithdrawalsStatusProcessing WithdrawalsStatus = "processing"
	WithdrawalsStatusSuccess    WithdrawalsStatus = "success"
	WithdrawalsStatusFailed     WithdrawalsStatus = "failed"
)

func (e *WithdrawalsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WithdrawalsStatus(s)
	case string:
		*e = WithdrawalsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WithdrawalsStatus: %T", src)
	}
	return nil
}

type NullWithdrawalsStatus struct {
	WithdrawalsStatus WithdrawalsStatus `json:"withdrawalsStatus"`
	Valid             bool              `json:"valid"` // Valid is true if WithdrawalsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWithdrawalsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WithdrawalsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WithdrawalsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWithdrawalsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WithdrawalsStatus), nil
}

type AdminUser struct {
	ID           string           `json:"id"`
	StoreID      string           `json:"storeId"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"passwordHash"`
	Role         AdminUsersRole   `json:"role"`
	Status       AdminUsersStatus `json:"status"`
	LastActiveAt sql.NullTime     `json:"lastActiveAt"`
	CreatedAt    time.Time        `json:"createdAt"`
	UpdatedAt    time.Time        `json:"updatedAt"`
	Username     sql.NullString   `json:"username"`
}

type CashMovement struct {
	ID         string            `json:"id"`
	StoreID    string            `json:"storeId"`
	ShiftID    sql.NullString    `json:"shiftId"`
	Type       CashMovementsType `json:"type"`
	Amount     int64             `json:"amount"`
	Notes      sql.NullString    `json:"notes"`
	CreatedBy  sql.NullString    `json:"createdBy"`
	ApprovedBy sql.NullString    `json:"approvedBy"`
	CreatedAt  time.Time         `json:"createdAt"`
}

type DiningTable struct {
	ID        string             `json:"id"`
	StoreID   string             `json:"storeId"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Area      string             `json:"area"`
	Seats     int32              `json:"seats"`
	Status    DiningTablesStatus `json:"status"`
	CreatedAt time.Time          `json:"createdAt"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

type IdempotencyKey struct {
	ID             string         `json:"id"`
	StoreID        string         `json:"storeId"`
	IdempotencyKey string         `json:"idempotencyKey"`
	RequestHash    string         `json:"requestHash"`
	ResponseStatus sql.NullInt32  `json:"responseStatus"`
	ResponseBody   sql.NullString `json:"responseBody"`
	CreatedAt      time.Time      `json:"createdAt"`
}

type Payment struct {
	ID          string           `json:"id"`
	StoreID     string           `json:"storeId"`
	SelfOrderID string           `json:"selfOrderId"`
	Provider    PaymentsProvider `json:"provider"`
	ProviderRef sql.NullString   `json:"providerRef"`
	Method      PaymentsMethod   `json:"method"`
	Amount      int64            `json:"amount"`
	Status      PaymentsStatus   `json:"status"`
	RawPayload  sql.NullString   `json:"rawPayload"`
	CreatedAt   time.Time        `json:"createdAt"`
	UpdatedAt   time.Time        `json:"updatedAt"`
}

type Product struct {
	ID         string         `json:"id"`
	StoreID    string         `json:"storeId"`
	CategoryID sql.NullString `json:"categoryId"`
	Sku        sql.NullString `json:"sku"`
	Name       string         `json:"name"`
	Price      int64          `json:"price"`
	Cost       int64          `json:"cost"`
	Stock      int32          `json:"stock"`
	Status     ProductsStatus `json:"status"`
	ImageUrl   sql.NullString `json:"imageUrl"`
	CreatedAt  time.Time      `json:"createdAt"`
	UpdatedAt  time.Time      `json:"updatedAt"`
}

type ProductCategory struct {
	ID        string    `json:"id"`
	StoreID   string    `json:"storeId"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sortOrder"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type RefreshToken struct {
	ID        string             `json:"id"`
	Actor     RefreshTokensActor `json:"actor"`
	SubjectID string             `json:"subjectId"`
	TokenHash string             `json:"tokenHash"`
	ExpiresAt time.Time          `json:"expiresAt"`
	RevokedAt sql.NullTime       `json:"revokedAt"`
	CreatedAt time.Time          `json:"createdAt"`
}

type SelfOrder struct {
	ID            string                  `json:"id"`
	StoreID       string                  `json:"storeId"`
	TableID       sql.NullString          `json:"tableId"`
	Status        SelfOrdersStatus        `json:"status"`
	PaymentMethod SelfOrdersPaymentMethod `json:"paymentMethod"`
	PaymentStatus SelfOrdersPaymentStatus `json:"paymentStatus"`
	ClaimCode     sql.NullString          `json:"claimCode"`
	Subtotal      int64                   `json:"subtotal"`
	Total         int64                   `json:"total"`
	CustomerNote  sql.NullString          `json:"customerNote"`
	TransactionID sql.NullString          `json:"transactionId"`
	ExpiresAt     sql.NullTime            `json:"expiresAt"`
	CreatedAt     time.Time               `json:"createdAt"`
	UpdatedAt     time.Time               `json:"updatedAt"`
}

type SelfOrderItem struct {
	ID          string         `json:"id"`
	SelfOrderID string         `json:"selfOrderId"`
	ProductID   sql.NullString `json:"productId"`
	ProductName string         `json:"productName"`
	Category    string         `json:"category"`
	Price       int64          `json:"price"`
	Quantity    int32          `json:"quantity"`
	LineTotal   int64          `json:"lineTotal"`
	Note        sql.NullString `json:"note"`
	CreatedAt   time.Time      `json:"createdAt"`
}

type Setting struct {
	ID                    string    `json:"id"`
	StoreID               string    `json:"storeId"`
	MaxDiscountPercent    int32     `json:"maxDiscountPercent"`
	MaxOperationalExpense int64     `json:"maxOperationalExpense"`
	CashVarianceTolerance int64     `json:"cashVarianceTolerance"`
	FeatureSelfOrder      bool      `json:"featureSelfOrder"`
	FeatureQris           bool      `json:"featureQris"`
	CreatedAt             time.Time `json:"createdAt"`
	UpdatedAt             time.Time `json:"updatedAt"`
}

type Shift struct {
	ID                string         `json:"id"`
	StoreID           string         `json:"storeId"`
	StaffID           string         `json:"staffId"`
	Status            ShiftsStatus   `json:"status"`
	InitialCash       int64          `json:"initialCash"`
	CashSales         int64          `json:"cashSales"`
	QrisSales         int64          `json:"qrisSales"`
	AdditionalCapital int64          `json:"additionalCapital"`
	Expenses          int64          `json:"expenses"`
	Withdrawals       int64          `json:"withdrawals"`
	Adjustments       int64          `json:"adjustments"`
	DrawerOpenCount   int32          `json:"drawerOpenCount"`
	ExpectedCash      sql.NullInt64  `json:"expectedCash"`
	ActualCash        sql.NullInt64  `json:"actualCash"`
	Variance          sql.NullInt64  `json:"variance"`
	CloseApprovedBy   sql.NullString `json:"closeApprovedBy"`
	OpenedAt          time.Time      `json:"openedAt"`
	ClosedAt          sql.NullTime   `json:"closedAt"`
	CreatedAt         time.Time      `json:"createdAt"`
	UpdatedAt         time.Time      `json:"updatedAt"`
}

type Staff struct {
	ID           string         `json:"id"`
	StoreID      string         `json:"storeId"`
	Name         string         `json:"name"`
	Username     string         `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"passwordHash"`
	Role         StaffRole      `json:"role"`
	Status       StaffStatus    `json:"status"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

type Store struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Type      string         `json:"type"`
	Address   sql.NullString `json:"address"`
	Phone     sql.NullString `json:"phone"`
	Timezone  string         `json:"timezone"`
	Currency  string         `json:"currency"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

type Transaction struct {
	ID                 string                    `json:"id"`
	StoreID            string                    `json:"storeId"`
	Code               string                    `json:"code"`
	ShiftID            sql.NullString            `json:"shiftId"`
	TableID            sql.NullString            `json:"tableId"`
	SelfOrderID        sql.NullString            `json:"selfOrderId"`
	CashierID          sql.NullString            `json:"cashierId"`
	OrderType          TransactionsOrderType     `json:"orderType"`
	Source             TransactionsSource        `json:"source"`
	PaymentMethod      TransactionsPaymentMethod `json:"paymentMethod"`
	Status             TransactionsStatus        `json:"status"`
	Subtotal           int64                     `json:"subtotal"`
	Discount           int64                     `json:"discount"`
	Tax                int64                     `json:"tax"`
	Total              int64                     `json:"total"`
	AmountReceived     int64                     `json:"amountReceived"`
	ChangeAmount       int64                     `json:"changeAmount"`
	DiscountApprovedBy sql.NullString            `json:"discountApprovedBy"`
	CustomerNote       sql.NullString            `json:"customerNote"`
	CreatedAt          time.Time                 `json:"createdAt"`
}

type TransactionItem struct {
	ID            string         `json:"id"`
	TransactionID string         `json:"transactionId"`
	ProductID     sql.NullString `json:"productId"`
	ProductName   string         `json:"productName"`
	Category      string         `json:"category"`
	Price         int64          `json:"price"`
	Quantity      int32          `json:"quantity"`
	LineTotal     int64          `json:"lineTotal"`
	Note          sql.NullString `json:"note"`
	CreatedAt     time.Time      `json:"createdAt"`
}

type WebhookEvent struct {
	ID          string    `json:"id"`
	Provider    string    `json:"provider"`
	EventID     string    `json:"eventId"`
	ProcessedAt time.Time `json:"processedAt"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Withdrawal struct {
	ID          string            `json:"id"`
	StoreID     string            `json:"storeId"`
	Amount      int64             `json:"amount"`
	Bank        string            `json:"bank"`
	Account     string            `json:"account"`
	Holder      string            `json:"holder"`
	Status      WithdrawalsStatus `json:"status"`
	Reference   sql.NullString    `json:"reference"`
	RequestedBy sql.NullString    `json:"requestedBy"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}
