// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payment.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countPaymentGatewayConfig = `-- name: CountPaymentGatewayConfig :one
SELECT COUNT(*) FROM payment_gateway_config
`

func (q *Queries) CountPaymentGatewayConfig(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPaymentGatewayConfig)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChargeApp = `-- name: CreateChargeApp :exec
INSERT INTO payment_charge_apps (order_ref, app_id, provider_ref) VALUES (?, ?, ?)
`

type CreateChargeAppParams struct {
	OrderRef    string         `json:"orderRef"`
	AppID       string         `json:"appId"`
	ProviderRef sql.NullString `json:"providerRef"`
}

func (q *Queries) CreateChargeApp(ctx context.Context, arg CreateChargeAppParams) error {
	_, err := q.db.ExecContext(ctx, createChargeApp, arg.OrderRef, arg.AppID, arg.ProviderRef)
	return err
}

const createPaymentClient = `-- name: CreatePaymentClient :exec
INSERT INTO payment_clients (id, app_id, name, secret_hash, secret_enc, kind, callback_url, status)
VALUES (?, ?, ?, ?, ?, ?, ?, 'active')
`

type CreatePaymentClientParams struct {
	ID          string             `json:"id"`
	AppID       string             `json:"appId"`
	Name        string             `json:"name"`
	SecretHash  sql.NullString     `json:"secretHash"`
	SecretEnc   sql.NullString     `json:"secretEnc"`
	Kind        PaymentClientsKind `json:"kind"`
	CallbackUrl sql.NullString     `json:"callbackUrl"`
}

func (q *Queries) CreatePaymentClient(ctx context.Context, arg CreatePaymentClientParams) error {
	_, err := q.db.ExecContext(ctx, createPaymentClient,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.SecretHash,
		arg.SecretEnc,
		arg.Kind,
		arg.CallbackUrl,
	)
	return err
}

const getChargeApp = `-- name: GetChargeApp :one
SELECT app_id FROM payment_charge_apps WHERE order_ref = ? LIMIT 1
`

func (q *Queries) GetChargeApp(ctx context.Context, orderRef string) (string, error) {
	row := q.db.QueryRowContext(ctx, getChargeApp, orderRef)
	var app_id string
	err := row.Scan(&app_id)
	return app_id, err
}

const getChargeAppByOrderRef = `-- name: GetChargeAppByOrderRef :one
SELECT app_id, provider_ref FROM payment_charge_apps WHERE order_ref = ? LIMIT 1
`

type GetChargeAppByOrderRefRow struct {
	AppID       string         `json:"appId"`
	ProviderRef sql.NullString `json:"providerRef"`
}

// Termasuk provider_ref (§10.2 EB2) — dipakai endpoint status eksternal untuk menerjemahkan
// orderRef milik pemanggil ke providerRef yang CheckStatus benar-benar butuhkan.
func (q *Queries) GetChargeAppByOrderRef(ctx context.Context, orderRef string) (GetChargeAppByOrderRefRow, error) {
	row := q.db.QueryRowContext(ctx, getChargeAppByOrderRef, orderRef)
	var i GetChargeAppByOrderRefRow
	err := row.Scan(&i.AppID, &i.ProviderRef)
	return i, err
}

const getPaymentClientByAppID = `-- name: GetPaymentClientByAppID :one
SELECT id, app_id, name, secret_hash, kind, callback_url, status, created_at, updated_at, secret_enc FROM payment_clients WHERE app_id = ? LIMIT 1
`

func (q *Queries) GetPaymentClientByAppID(ctx context.Context, appID string) (PaymentClient, error) {
	row := q.db.QueryRowContext(ctx, getPaymentClientByAppID, appID)
	var i PaymentClient
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.SecretHash,
		&i.Kind,
		&i.CallbackUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretEnc,
	)
	return i, err
}

const getPaymentClientByID = `-- name: GetPaymentClientByID :one
SELECT id, app_id, name, secret_hash, kind, callback_url, status, created_at, updated_at, secret_enc FROM payment_clients WHERE id = ? LIMIT 1
`

func (q *Queries) GetPaymentClientByID(ctx context.Context, id string) (PaymentClient, error) {
	row := q.db.QueryRowContext(ctx, getPaymentClientByID, id)
	var i PaymentClient
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.SecretHash,
		&i.Kind,
		&i.CallbackUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretEnc,
	)
	return i, err
}

const getPaymentClientSecretEnc = `-- name: GetPaymentClientSecretEnc :one
SELECT secret_enc FROM payment_clients WHERE id = ? AND kind = 'external' LIMIT 1
`

// Dipakai HANYA saat menandatangani relay webhook keluar (§10.1.6/§10.1.10) — bukan untuk
// otentikasi masuk (itu pakai secret_hash via GetPaymentClientByAppID/ByID + bcrypt compare).
func (q *Queries) GetPaymentClientSecretEnc(ctx context.Context, id string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getPaymentClientSecretEnc, id)
	var secret_enc sql.NullString
	err := row.Scan(&secret_enc)
	return secret_enc, err
}

const getPaymentGatewayConfig = `-- name: GetPaymentGatewayConfig :one
SELECT id, provider, sandbox, tripay_api_key_enc, tripay_private_key_enc, tripay_merchant_code_enc, tripay_method, midtrans_server_key_enc, created_at, updated_at FROM payment_gateway_config LIMIT 1
`

func (q *Queries) GetPaymentGatewayConfig(ctx context.Context) (PaymentGatewayConfig, error) {
	row := q.db.QueryRowContext(ctx, getPaymentGatewayConfig)
	var i PaymentGatewayConfig
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Sandbox,
		&i.TripayApiKeyEnc,
		&i.TripayPrivateKeyEnc,
		&i.TripayMerchantCodeEnc,
		&i.TripayMethod,
		&i.MidtransServerKeyEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPaymentGatewayConfig = `-- name: InsertPaymentGatewayConfig :exec
INSERT INTO payment_gateway_config (
  id, provider, sandbox, tripay_api_key_enc, tripay_private_key_enc, tripay_merchant_code_enc,
  tripay_method, midtrans_server_key_enc
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPaymentGatewayConfigParams struct {
	ID                    string         `json:"id"`
	Provider              string         `json:"provider"`
	Sandbox               bool           `json:"sandbox"`
	TripayApiKeyEnc       sql.NullString `json:"tripayApiKeyEnc"`
	TripayPrivateKeyEnc   sql.NullString `json:"tripayPrivateKeyEnc"`
	TripayMerchantCodeEnc sql.NullString `json:"tripayMerchantCodeEnc"`
	TripayMethod          string         `json:"tripayMethod"`
	MidtransServerKeyEnc  sql.NullString `json:"midtransServerKeyEnc"`
}

func (q *Queries) InsertPaymentGatewayConfig(ctx context.Context, arg InsertPaymentGatewayConfigParams) error {
	_, err := q.db.ExecContext(ctx, insertPaymentGatewayConfig,
		arg.ID,
		arg.Provider,
		arg.Sandbox,
		arg.TripayApiKeyEnc,
		arg.TripayPrivateKeyEnc,
		arg.TripayMerchantCodeEnc,
		arg.TripayMethod,
		arg.MidtransServerKeyEnc,
	)
	return err
}

const listPaymentClients = `-- name: ListPaymentClients :many
SELECT id, app_id, name, secret_hash, kind, callback_url, status, created_at, updated_at, secret_enc FROM payment_clients ORDER BY created_at ASC
`

func (q *Queries) ListPaymentClients(ctx context.Context) ([]PaymentClient, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentClient{}
	for rows.Next() {
		var i PaymentClient
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.SecretHash,
			&i.Kind,
			&i.CallbackUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SecretEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentClientSecret = `-- name: SetPaymentClientSecret :execrows
UPDATE payment_clients SET secret_hash = ?, secret_enc = ? WHERE id = ? AND kind = 'external'
`

type SetPaymentClientSecretParams struct {
	SecretHash sql.NullString `json:"secretHash"`
	SecretEnc  sql.NullString `json:"secretEnc"`
	ID         string         `json:"id"`
}

func (q *Queries) SetPaymentClientSecret(ctx context.Context, arg SetPaymentClientSecretParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPaymentClientSecret, arg.SecretHash, arg.SecretEnc, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPaymentClientStatus = `-- name: SetPaymentClientStatus :execrows
UPDATE payment_clients SET status = ? WHERE id = ? AND kind = 'external'
`

type SetPaymentClientStatusParams struct {
	Status PaymentClientsStatus `json:"status"`
	ID     string               `json:"id"`
}

func (q *Queries) SetPaymentClientStatus(ctx context.Context, arg SetPaymentClientStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPaymentClientStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePaymentGatewayConfig = `-- name: UpdatePaymentGatewayConfig :exec
UPDATE payment_gateway_config SET
  provider = ?, sandbox = ?, tripay_api_key_enc = ?, tripay_private_key_enc = ?,
  tripay_merchant_code_enc = ?, tripay_method = ?, midtrans_server_key_enc = ?
WHERE id = ?
`

type UpdatePaymentGatewayConfigParams struct {
	Provider              string         `json:"provider"`
	Sandbox               bool           `json:"sandbox"`
	TripayApiKeyEnc       sql.NullString `json:"tripayApiKeyEnc"`
	TripayPrivateKeyEnc   sql.NullString `json:"tripayPrivateKeyEnc"`
	TripayMerchantCodeEnc sql.NullString `json:"tripayMerchantCodeEnc"`
	TripayMethod          string         `json:"tripayMethod"`
	MidtransServerKeyEnc  sql.NullString `json:"midtransServerKeyEnc"`
	ID                    string         `json:"id"`
}

func (q *Queries) UpdatePaymentGatewayConfig(ctx context.Context, arg UpdatePaymentGatewayConfigParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentGatewayConfig,
		arg.Provider,
		arg.Sandbox,
		arg.TripayApiKeyEnc,
		arg.TripayPrivateKeyEnc,
		arg.TripayMerchantCodeEnc,
		arg.TripayMethod,
		arg.MidtransServerKeyEnc,
		arg.ID,
	)
	return err
}
