// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payment.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countPaymentGatewayConfig = `-- name: CountPaymentGatewayConfig :one
SELECT COUNT(*) FROM payment_gateway_config
`

func (q *Queries) CountPaymentGatewayConfig(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPaymentGatewayConfig)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChargeApp = `-- name: CreateChargeApp :exec
INSERT INTO payment_charge_apps (order_ref, app_id) VALUES (?, ?)
`

type CreateChargeAppParams struct {
	OrderRef string `json:"orderRef"`
	AppID    string `json:"appId"`
}

func (q *Queries) CreateChargeApp(ctx context.Context, arg CreateChargeAppParams) error {
	_, err := q.db.ExecContext(ctx, createChargeApp, arg.OrderRef, arg.AppID)
	return err
}

const getChargeApp = `-- name: GetChargeApp :one
SELECT app_id FROM payment_charge_apps WHERE order_ref = ? LIMIT 1
`

func (q *Queries) GetChargeApp(ctx context.Context, orderRef string) (string, error) {
	row := q.db.QueryRowContext(ctx, getChargeApp, orderRef)
	var app_id string
	err := row.Scan(&app_id)
	return app_id, err
}

const getPaymentGatewayConfig = `-- name: GetPaymentGatewayConfig :one
SELECT id, provider, sandbox, tripay_api_key_enc, tripay_private_key_enc, tripay_merchant_code_enc, tripay_method, midtrans_server_key_enc, created_at, updated_at, elproof_app_id, elproof_secret_enc, elproof_base_url FROM payment_gateway_config LIMIT 1
`

func (q *Queries) GetPaymentGatewayConfig(ctx context.Context) (PaymentGatewayConfig, error) {
	row := q.db.QueryRowContext(ctx, getPaymentGatewayConfig)
	var i PaymentGatewayConfig
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Sandbox,
		&i.TripayApiKeyEnc,
		&i.TripayPrivateKeyEnc,
		&i.TripayMerchantCodeEnc,
		&i.TripayMethod,
		&i.MidtransServerKeyEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ElproofAppID,
		&i.ElproofSecretEnc,
		&i.ElproofBaseUrl,
	)
	return i, err
}

const insertPaymentGatewayConfig = `-- name: InsertPaymentGatewayConfig :exec
INSERT INTO payment_gateway_config (
  id, provider, sandbox, tripay_api_key_enc, tripay_private_key_enc, tripay_merchant_code_enc,
  tripay_method, midtrans_server_key_enc
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPaymentGatewayConfigParams struct {
	ID                    string         `json:"id"`
	Provider              string         `json:"provider"`
	Sandbox               bool           `json:"sandbox"`
	TripayApiKeyEnc       sql.NullString `json:"tripayApiKeyEnc"`
	TripayPrivateKeyEnc   sql.NullString `json:"tripayPrivateKeyEnc"`
	TripayMerchantCodeEnc sql.NullString `json:"tripayMerchantCodeEnc"`
	TripayMethod          string         `json:"tripayMethod"`
	MidtransServerKeyEnc  sql.NullString `json:"midtransServerKeyEnc"`
}

func (q *Queries) InsertPaymentGatewayConfig(ctx context.Context, arg InsertPaymentGatewayConfigParams) error {
	_, err := q.db.ExecContext(ctx, insertPaymentGatewayConfig,
		arg.ID,
		arg.Provider,
		arg.Sandbox,
		arg.TripayApiKeyEnc,
		arg.TripayPrivateKeyEnc,
		arg.TripayMerchantCodeEnc,
		arg.TripayMethod,
		arg.MidtransServerKeyEnc,
	)
	return err
}

const updatePaymentGatewayConfig = `-- name: UpdatePaymentGatewayConfig :exec
UPDATE payment_gateway_config SET
  provider = ?, sandbox = ?, tripay_api_key_enc = ?, tripay_private_key_enc = ?,
  tripay_merchant_code_enc = ?, tripay_method = ?, midtrans_server_key_enc = ?,
  elproof_app_id = ?, elproof_secret_enc = ?, elproof_base_url = ?
WHERE id = ?
`

type UpdatePaymentGatewayConfigParams struct {
	Provider              string         `json:"provider"`
	Sandbox               bool           `json:"sandbox"`
	TripayApiKeyEnc       sql.NullString `json:"tripayApiKeyEnc"`
	TripayPrivateKeyEnc   sql.NullString `json:"tripayPrivateKeyEnc"`
	TripayMerchantCodeEnc sql.NullString `json:"tripayMerchantCodeEnc"`
	TripayMethod          string         `json:"tripayMethod"`
	MidtransServerKeyEnc  sql.NullString `json:"midtransServerKeyEnc"`
	ElproofAppID          sql.NullString `json:"elproofAppId"`
	ElproofSecretEnc      sql.NullString `json:"elproofSecretEnc"`
	ElproofBaseUrl        string         `json:"elproofBaseUrl"`
	ID                    string         `json:"id"`
}

// ElProof (elproof_*) is a SEPARATE, always-on wallet used only for subscription billing
// (paymentclient.AppSubscribe) — not part of the Provider switch above (§11).
func (q *Queries) UpdatePaymentGatewayConfig(ctx context.Context, arg UpdatePaymentGatewayConfigParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentGatewayConfig,
		arg.Provider,
		arg.Sandbox,
		arg.TripayApiKeyEnc,
		arg.TripayPrivateKeyEnc,
		arg.TripayMerchantCodeEnc,
		arg.TripayMethod,
		arg.MidtransServerKeyEnc,
		arg.ElproofAppID,
		arg.ElproofSecretEnc,
		arg.ElproofBaseUrl,
		arg.ID,
	)
	return err
}
