// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payments.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (id, store_id, self_order_id, provider, provider_ref, method, amount, status, raw_payload)
VALUES (?, ?, ?, ?, ?, 'qris', ?, ?, ?)
`

type CreatePaymentParams struct {
	ID          string           `json:"id"`
	StoreID     string           `json:"storeId"`
	SelfOrderID string           `json:"selfOrderId"`
	Provider    PaymentsProvider `json:"provider"`
	ProviderRef sql.NullString   `json:"providerRef"`
	Amount      int64            `json:"amount"`
	Status      PaymentsStatus   `json:"status"`
	RawPayload  sql.NullString   `json:"rawPayload"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.ID,
		arg.StoreID,
		arg.SelfOrderID,
		arg.Provider,
		arg.ProviderRef,
		arg.Amount,
		arg.Status,
		arg.RawPayload,
	)
	return err
}

const createWebhookEvent = `-- name: CreateWebhookEvent :exec
INSERT INTO webhook_events (id, provider, event_id) VALUES (?, ?, ?)
`

type CreateWebhookEventParams struct {
	ID       string `json:"id"`
	Provider string `json:"provider"`
	EventID  string `json:"eventId"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) error {
	_, err := q.db.ExecContext(ctx, createWebhookEvent, arg.ID, arg.Provider, arg.EventID)
	return err
}

const getPaymentByProviderRef = `-- name: GetPaymentByProviderRef :one
SELECT id, store_id, self_order_id, provider_ref, method, amount, status, raw_payload, created_at, updated_at, provider FROM payments WHERE provider_ref = ? LIMIT 1
`

func (q *Queries) GetPaymentByProviderRef(ctx context.Context, providerRef sql.NullString) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByProviderRef, providerRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SelfOrderID,
		&i.ProviderRef,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
	)
	return i, err
}

const getPaymentBySelfOrder = `-- name: GetPaymentBySelfOrder :one
SELECT id, store_id, self_order_id, provider_ref, method, amount, status, raw_payload, created_at, updated_at, provider FROM payments WHERE self_order_id = ? ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetPaymentBySelfOrder(ctx context.Context, selfOrderID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentBySelfOrder, selfOrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SelfOrderID,
		&i.ProviderRef,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
	)
	return i, err
}

const getWebhookEvent = `-- name: GetWebhookEvent :one
SELECT id, provider, event_id, processed_at, created_at FROM webhook_events WHERE provider = ? AND event_id = ? LIMIT 1
`

type GetWebhookEventParams struct {
	Provider string `json:"provider"`
	EventID  string `json:"eventId"`
}

func (q *Queries) GetWebhookEvent(ctx context.Context, arg GetWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEvent, arg.Provider, arg.EventID)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventID,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET status = ?, raw_payload = ? WHERE id = ?
`

type UpdatePaymentStatusParams struct {
	Status     PaymentsStatus `json:"status"`
	RawPayload sql.NullString `json:"rawPayload"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus, arg.Status, arg.RawPayload, arg.ID)
	return err
}
