// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: platform.sql

package sqlcgen

import (
	"context"
	"time"
)

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, name, slug, status, created_at FROM stores WHERE id = ? LIMIT 1
`

type GetStoreByIDRow struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Slug      string       `json:"slug"`
	Status    StoresStatus `json:"status"`
	CreatedAt time.Time    `json:"createdAt"`
}

func (q *Queries) GetStoreByID(ctx context.Context, id string) (GetStoreByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getStoreByID, id)
	var i GetStoreByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listStores = `-- name: ListStores :many

SELECT id, name, slug, status, created_at FROM stores ORDER BY created_at DESC
`

type ListStoresRow struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Slug      string       `json:"slug"`
	Status    StoresStatus `json:"status"`
	CreatedAt time.Time    `json:"createdAt"`
}

// Tabel `stores` dimiliki shared-kernel; kolom siklus-hidup (slug, status) dibaca/ditulis
// modul `platform` sebagai pengecualian shared-kernel kedua (setelah `settings` untuk kolom
// profil) — lihat knowledge/MODULE_MAP.md.
func (q *Queries) ListStores(ctx context.Context) ([]ListStoresRow, error) {
	rows, err := q.db.QueryContext(ctx, listStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoresRow{}
	for rows.Next() {
		var i ListStoresRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoreStatus = `-- name: UpdateStoreStatus :execrows
UPDATE stores SET status = ? WHERE id = ?
`

type UpdateStoreStatusParams struct {
	Status StoresStatus `json:"status"`
	ID     string       `json:"id"`
}

func (q *Queries) UpdateStoreStatus(ctx context.Context, arg UpdateStoreStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateStoreStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
