// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: platformusers.sql

package sqlcgen

import (
	"context"
)

const createPlatformUser = `-- name: CreatePlatformUser :exec
INSERT INTO platform_users (id, name, email, password_hash, status)
VALUES (?, ?, ?, ?, ?)
`

type CreatePlatformUserParams struct {
	ID           string              `json:"id"`
	Name         string              `json:"name"`
	Email        string              `json:"email"`
	PasswordHash string              `json:"passwordHash"`
	Status       PlatformUsersStatus `json:"status"`
}

func (q *Queries) CreatePlatformUser(ctx context.Context, arg CreatePlatformUserParams) error {
	_, err := q.db.ExecContext(ctx, createPlatformUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
	)
	return err
}

const getPlatformUser = `-- name: GetPlatformUser :one
SELECT id, name, email, password_hash, status, created_at, updated_at FROM platform_users WHERE id = ? LIMIT 1
`

func (q *Queries) GetPlatformUser(ctx context.Context, id string) (PlatformUser, error) {
	row := q.db.QueryRowContext(ctx, getPlatformUser, id)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlatformUsers = `-- name: ListPlatformUsers :many
SELECT id, name, email, password_hash, status, created_at, updated_at FROM platform_users ORDER BY created_at ASC
`

func (q *Queries) ListPlatformUsers(ctx context.Context) ([]PlatformUser, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformUser{}
	for rows.Next() {
		var i PlatformUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlatformUserStatus = `-- name: SetPlatformUserStatus :execrows
UPDATE platform_users SET status = ? WHERE id = ?
`

type SetPlatformUserStatusParams struct {
	Status PlatformUsersStatus `json:"status"`
	ID     string              `json:"id"`
}

func (q *Queries) SetPlatformUserStatus(ctx context.Context, arg SetPlatformUserStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPlatformUserStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePlatformUserPassword = `-- name: UpdatePlatformUserPassword :exec
UPDATE platform_users SET password_hash = ? WHERE id = ?
`

type UpdatePlatformUserPasswordParams struct {
	PasswordHash string `json:"passwordHash"`
	ID           string `json:"id"`
}

func (q *Queries) UpdatePlatformUserPassword(ctx context.Context, arg UpdatePlatformUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePlatformUserPassword, arg.PasswordHash, arg.ID)
	return err
}
