// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: products.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const adjustProductStock = `-- name: AdjustProductStock :execrows
UPDATE products SET stock = stock + ? WHERE id = ? AND store_id = ?
`

type AdjustProductStockParams struct {
	Stock   int32  `json:"stock"`
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) AdjustProductStock(ctx context.Context, arg AdjustProductStockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, adjustProductStock, arg.Stock, arg.ID, arg.StoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (id, store_id, category_id, sku, name, price, cost, stock, status, image_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProductParams struct {
	ID         string         `json:"id"`
	StoreID    string         `json:"storeId"`
	CategoryID sql.NullString `json:"categoryId"`
	Sku        sql.NullString `json:"sku"`
	Name       string         `json:"name"`
	Price      int64          `json:"price"`
	Cost       int64          `json:"cost"`
	Stock      int32          `json:"stock"`
	Status     ProductsStatus `json:"status"`
	ImageUrl   sql.NullString `json:"imageUrl"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.StoreID,
		arg.CategoryID,
		arg.Sku,
		arg.Name,
		arg.Price,
		arg.Cost,
		arg.Stock,
		arg.Status,
		arg.ImageUrl,
	)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = ? AND store_id = ?
`

type DeleteProductParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, arg.ID, arg.StoreID)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, store_id, category_id, sku, name, price, cost, stock, status, image_url, created_at, updated_at FROM products WHERE id = ? AND store_id = ? LIMIT 1
`

type GetProductParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, arg.ID, arg.StoreID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CategoryID,
		&i.Sku,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.Stock,
		&i.Status,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET category_id = ?, sku = ?, name = ?, price = ?, cost = ?, stock = ?, status = ?, image_url = ?
WHERE id = ? AND store_id = ?
`

type UpdateProductParams struct {
	CategoryID sql.NullString `json:"categoryId"`
	Sku        sql.NullString `json:"sku"`
	Name       string         `json:"name"`
	Price      int64          `json:"price"`
	Cost       int64          `json:"cost"`
	Stock      int32          `json:"stock"`
	Status     ProductsStatus `json:"status"`
	ImageUrl   sql.NullString `json:"imageUrl"`
	ID         string         `json:"id"`
	StoreID    string         `json:"storeId"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.CategoryID,
		arg.Sku,
		arg.Name,
		arg.Price,
		arg.Cost,
		arg.Stock,
		arg.Status,
		arg.ImageUrl,
		arg.ID,
		arg.StoreID,
	)
	return err
}
