// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	AdjustProductStock(ctx context.Context, arg AdjustProductStockParams) (int64, error)
	CloseShift(ctx context.Context, arg CloseShiftParams) (int64, error)
	CountCashMovements(ctx context.Context, storeID string) (int64, error)
	CountShifts(ctx context.Context, storeID string) (int64, error)
	CountWithdrawals(ctx context.Context, storeID string) (int64, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error
	CreateCashMovement(ctx context.Context, arg CreateCashMovementParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateSelfOrder(ctx context.Context, arg CreateSelfOrderParams) error
	CreateSelfOrderItem(ctx context.Context, arg CreateSelfOrderItemParams) error
	CreateShift(ctx context.Context, arg CreateShiftParams) error
	CreateStaff(ctx context.Context, arg CreateStaffParams) error
	CreateTable(ctx context.Context, arg CreateTableParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) error
	CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) error
	CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) error
	// Kurangi stok dengan penjaga stok >= qty (cegah stok negatif). 0 rows = gagal.
	DecrementStock(ctx context.Context, arg DecrementStockParams) (int64, error)
	DeleteAdminUser(ctx context.Context, arg DeleteAdminUserParams) error
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteStaff(ctx context.Context, arg DeleteStaffParams) error
	DeleteTable(ctx context.Context, arg DeleteTableParams) error
	ExpireOverdueSelfOrders(ctx context.Context, arg ExpireOverdueSelfOrdersParams) (int64, error)
	FindTableByCode(ctx context.Context, code string) (DiningTable, error)
	GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error)
	GetAdminUserByEmailOrUsername(ctx context.Context, arg GetAdminUserByEmailOrUsernameParams) (AdminUser, error)
	GetAdminUserByID(ctx context.Context, id string) (AdminUser, error)
	GetAdminUserScoped(ctx context.Context, arg GetAdminUserScopedParams) (AdminUser, error)
	GetCashMovement(ctx context.Context, arg GetCashMovementParams) (CashMovement, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (ProductCategory, error)
	GetFirstStore(ctx context.Context) (Store, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetOpenShift(ctx context.Context, storeID string) (Shift, error)
	GetPaymentByProviderRef(ctx context.Context, providerRef sql.NullString) (Payment, error)
	GetPaymentBySelfOrder(ctx context.Context, selfOrderID string) (Payment, error)
	GetProduct(ctx context.Context, arg GetProductParams) (Product, error)
	GetProductForSale(ctx context.Context, arg GetProductForSaleParams) (GetProductForSaleRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSelfOrder(ctx context.Context, arg GetSelfOrderParams) (SelfOrder, error)
	GetSelfOrderByClaimCode(ctx context.Context, arg GetSelfOrderByClaimCodeParams) (SelfOrder, error)
	GetSelfOrderByID(ctx context.Context, id string) (SelfOrder, error)
	// Tabel settings dimiliki modul `settings`. Pembaca lintas-modul memakai kontrak
	// settingsclient; query di sini adalah satu-satunya akses tulis.
	GetSettingsByStore(ctx context.Context, storeID string) (Setting, error)
	GetShift(ctx context.Context, arg GetShiftParams) (Shift, error)
	GetStaffByID(ctx context.Context, id string) (Staff, error)
	GetStaffByUsername(ctx context.Context, username string) (Staff, error)
	GetStaffScoped(ctx context.Context, arg GetStaffScopedParams) (Staff, error)
	GetTable(ctx context.Context, arg GetTableParams) (DiningTable, error)
	GetTableByCode(ctx context.Context, arg GetTableByCodeParams) (DiningTable, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error)
	GetWebhookEvent(ctx context.Context, arg GetWebhookEventParams) (WebhookEvent, error)
	ListActiveProducts(ctx context.Context, storeID string) ([]ListActiveProductsRow, error)
	ListAdminUsers(ctx context.Context, storeID string) ([]AdminUser, error)
	ListCashMovements(ctx context.Context, arg ListCashMovementsParams) ([]CashMovement, error)
	ListCategories(ctx context.Context, storeID string) ([]ListCategoriesRow, error)
	ListSelfOrderItems(ctx context.Context, selfOrderID string) ([]SelfOrderItem, error)
	ListShifts(ctx context.Context, arg ListShiftsParams) ([]Shift, error)
	ListStaff(ctx context.Context, storeID string) ([]Staff, error)
	ListSupervisorPins(ctx context.Context, storeID string) ([]ListSupervisorPinsRow, error)
	ListTables(ctx context.Context, storeID string) ([]DiningTable, error)
	ListTransactionItems(ctx context.Context, transactionID string) ([]TransactionItem, error)
	ListWithdrawals(ctx context.Context, arg ListWithdrawalsParams) ([]Withdrawal, error)
	MarkSelfOrderPaid(ctx context.Context, arg MarkSelfOrderPaidParams) error
	Ping(ctx context.Context) (int32, error)
	ReportPaymentDistribution(ctx context.Context, arg ReportPaymentDistributionParams) (ReportPaymentDistributionRow, error)
	ReportRecentTransactions(ctx context.Context, arg ReportRecentTransactionsParams) ([]ReportRecentTransactionsRow, error)
	ReportSalesByCategory(ctx context.Context, arg ReportSalesByCategoryParams) ([]ReportSalesByCategoryRow, error)
	ReportSalesByDay(ctx context.Context, arg ReportSalesByDayParams) ([]ReportSalesByDayRow, error)
	// revenue = total. Tiga bucket keuangan terpisah: penjualan (subtotal−diskon),
	// layanan (service + biaya gateway), pajak (PPN). Ketiganya berjumlah = revenue.
	ReportSalesSummary(ctx context.Context, arg ReportSalesSummaryParams) (ReportSalesSummaryRow, error)
	ReportStaffPerformance(ctx context.Context, arg ReportStaffPerformanceParams) ([]ReportStaffPerformanceRow, error)
	ReportTopProducts(ctx context.Context, arg ReportTopProductsParams) ([]ReportTopProductsRow, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	ShiftCashMovementSummary(ctx context.Context, shiftID sql.NullString) (ShiftCashMovementSummaryRow, error)
	ShiftSalesSummary(ctx context.Context, shiftID sql.NullString) (ShiftSalesSummaryRow, error)
	TouchAdminUserLastActive(ctx context.Context, arg TouchAdminUserLastActiveParams) error
	UpdateAdminUser(ctx context.Context, arg UpdateAdminUserParams) error
	UpdateAdminUserPassword(ctx context.Context, arg UpdateAdminUserPasswordParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateSelfOrderStatus(ctx context.Context, arg UpdateSelfOrderStatusParams) (int64, error)
	UpdateStaff(ctx context.Context, arg UpdateStaffParams) error
	UpdateStaffPassword(ctx context.Context, arg UpdateStaffPasswordParams) error
	UpdateStaffPin(ctx context.Context, arg UpdateStaffPinParams) error
	UpdateTable(ctx context.Context, arg UpdateTableParams) error
	UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error
	// Batalkan transaksi (void). Hanya transaksi 'completed' yang bisa dibatalkan; 0 rows =
	// tidak ditemukan / sudah dibatalkan. Pengecualian (tunai, dalam shift) ditegakkan di service.
	VoidTransaction(ctx context.Context, arg VoidTransactionParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
