// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reports.sql

package sqlcgen

import (
	"context"
	"time"
)

const reportPaymentDistribution = `-- name: ReportPaymentDistribution :one
SELECT
  CAST(COALESCE(SUM(CASE WHEN payment_method = 'cash' THEN total END), 0) AS SIGNED) AS cash_total,
  CAST(COALESCE(SUM(CASE WHEN payment_method = 'qris' THEN total END), 0) AS SIGNED) AS qris_total,
  CAST(COALESCE(SUM(CASE WHEN payment_method = 'cash' THEN 1 ELSE 0 END), 0) AS SIGNED) AS cash_count,
  CAST(COALESCE(SUM(CASE WHEN payment_method = 'qris' THEN 1 ELSE 0 END), 0) AS SIGNED) AS qris_count
FROM transactions
WHERE store_id = ? AND status = 'completed' AND created_at >= ? AND created_at < ?
`

type ReportPaymentDistributionParams struct {
	StoreID     string    `json:"storeId"`
	CreatedAt   time.Time `json:"createdAt"`
	CreatedAt_2 time.Time `json:"createdAt2"`
}

type ReportPaymentDistributionRow struct {
	CashTotal int64 `json:"cashTotal"`
	QrisTotal int64 `json:"qrisTotal"`
	CashCount int64 `json:"cashCount"`
	QrisCount int64 `json:"qrisCount"`
}

func (q *Queries) ReportPaymentDistribution(ctx context.Context, arg ReportPaymentDistributionParams) (ReportPaymentDistributionRow, error) {
	row := q.db.QueryRowContext(ctx, reportPaymentDistribution, arg.StoreID, arg.CreatedAt, arg.CreatedAt_2)
	var i ReportPaymentDistributionRow
	err := row.Scan(
		&i.CashTotal,
		&i.QrisTotal,
		&i.CashCount,
		&i.QrisCount,
	)
	return i, err
}

const reportRecentTransactions = `-- name: ReportRecentTransactions :many
SELECT id, code, source, payment_method, total, created_at
FROM transactions
WHERE store_id = ? AND status = 'completed'
ORDER BY created_at DESC
LIMIT ?
`

type ReportRecentTransactionsParams struct {
	StoreID string `json:"storeId"`
	Limit   int32  `json:"limit"`
}

type ReportRecentTransactionsRow struct {
	ID            string                    `json:"id"`
	Code          string                    `json:"code"`
	Source        TransactionsSource        `json:"source"`
	PaymentMethod TransactionsPaymentMethod `json:"paymentMethod"`
	Total         int64                     `json:"total"`
	CreatedAt     time.Time                 `json:"createdAt"`
}

func (q *Queries) ReportRecentTransactions(ctx context.Context, arg ReportRecentTransactionsParams) ([]ReportRecentTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, reportRecentTransactions, arg.StoreID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportRecentTransactionsRow{}
	for rows.Next() {
		var i ReportRecentTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Source,
			&i.PaymentMethod,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSalesByCategory = `-- name: ReportSalesByCategory :many
SELECT
  ti.category AS category,
  CAST(COALESCE(SUM(ti.line_total), 0) AS SIGNED) AS revenue,
  CAST(COALESCE(SUM(ti.quantity), 0) AS SIGNED) AS qty
FROM transaction_items ti
JOIN transactions t ON t.id = ti.transaction_id
WHERE t.store_id = ? AND t.status = 'completed' AND t.created_at >= ? AND t.created_at < ?
GROUP BY ti.category
ORDER BY revenue DESC
`

type ReportSalesByCategoryParams struct {
	StoreID     string    `json:"storeId"`
	CreatedAt   time.Time `json:"createdAt"`
	CreatedAt_2 time.Time `json:"createdAt2"`
}

type ReportSalesByCategoryRow struct {
	Category string `json:"category"`
	Revenue  int64  `json:"revenue"`
	Qty      int64  `json:"qty"`
}

func (q *Queries) ReportSalesByCategory(ctx context.Context, arg ReportSalesByCategoryParams) ([]ReportSalesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, reportSalesByCategory, arg.StoreID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSalesByCategoryRow{}
	for rows.Next() {
		var i ReportSalesByCategoryRow
		if err := rows.Scan(&i.Category, &i.Revenue, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSalesByDay = `-- name: ReportSalesByDay :many
SELECT
  DATE(created_at) AS day,
  COUNT(*) AS tx_count,
  CAST(COALESCE(SUM(total), 0) AS SIGNED) AS revenue
FROM transactions
WHERE store_id = ? AND status = 'completed' AND created_at >= ? AND created_at < ?
GROUP BY DATE(created_at)
ORDER BY day ASC
`

type ReportSalesByDayParams struct {
	StoreID     string    `json:"storeId"`
	CreatedAt   time.Time `json:"createdAt"`
	CreatedAt_2 time.Time `json:"createdAt2"`
}

type ReportSalesByDayRow struct {
	Day     time.Time `json:"day"`
	TxCount int64     `json:"txCount"`
	Revenue int64     `json:"revenue"`
}

func (q *Queries) ReportSalesByDay(ctx context.Context, arg ReportSalesByDayParams) ([]ReportSalesByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, reportSalesByDay, arg.StoreID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSalesByDayRow{}
	for rows.Next() {
		var i ReportSalesByDayRow
		if err := rows.Scan(&i.Day, &i.TxCount, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSalesSummary = `-- name: ReportSalesSummary :one
SELECT
  COUNT(*) AS tx_count,
  CAST(COALESCE(SUM(total), 0) AS SIGNED) AS revenue,
  CAST(COALESCE(SUM(subtotal - discount), 0) AS SIGNED) AS sales_total,
  CAST(COALESCE(SUM(service_charge + gateway_fee), 0) AS SIGNED) AS service_total,
  CAST(COALESCE(SUM(tax), 0) AS SIGNED) AS tax_total,
  CAST(COALESCE(SUM(CASE WHEN payment_method = 'cash' THEN total END), 0) AS SIGNED) AS cash_total,
  CAST(COALESCE(SUM(CASE WHEN payment_method = 'qris' THEN total END), 0) AS SIGNED) AS qris_total
FROM transactions
WHERE store_id = ? AND status = 'completed' AND created_at >= ? AND created_at < ?
`

type ReportSalesSummaryParams struct {
	StoreID     string    `json:"storeId"`
	CreatedAt   time.Time `json:"createdAt"`
	CreatedAt_2 time.Time `json:"createdAt2"`
}

type ReportSalesSummaryRow struct {
	TxCount      int64 `json:"txCount"`
	Revenue      int64 `json:"revenue"`
	SalesTotal   int64 `json:"salesTotal"`
	ServiceTotal int64 `json:"serviceTotal"`
	TaxTotal     int64 `json:"taxTotal"`
	CashTotal    int64 `json:"cashTotal"`
	QrisTotal    int64 `json:"qrisTotal"`
}

// revenue = total. Tiga bucket keuangan terpisah: penjualan (subtotal−diskon),
// layanan (service + biaya gateway), pajak (PPN). Ketiganya berjumlah = revenue.
func (q *Queries) ReportSalesSummary(ctx context.Context, arg ReportSalesSummaryParams) (ReportSalesSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, reportSalesSummary, arg.StoreID, arg.CreatedAt, arg.CreatedAt_2)
	var i ReportSalesSummaryRow
	err := row.Scan(
		&i.TxCount,
		&i.Revenue,
		&i.SalesTotal,
		&i.ServiceTotal,
		&i.TaxTotal,
		&i.CashTotal,
		&i.QrisTotal,
	)
	return i, err
}

const reportStaffPerformance = `-- name: ReportStaffPerformance :many
SELECT
  s.id AS staff_id,
  s.name AS name,
  CAST(COUNT(t.id) AS SIGNED) AS tx_count,
  CAST(COALESCE(SUM(t.total), 0) AS SIGNED) AS revenue
FROM staff s
LEFT JOIN transactions t
  ON t.cashier_id = s.id AND t.status = 'completed' AND t.created_at >= ? AND t.created_at < ?
WHERE s.store_id = ?
GROUP BY s.id, s.name
ORDER BY revenue DESC
`

type ReportStaffPerformanceParams struct {
	CreatedAt   time.Time `json:"createdAt"`
	CreatedAt_2 time.Time `json:"createdAt2"`
	StoreID     string    `json:"storeId"`
}

type ReportStaffPerformanceRow struct {
	StaffID string `json:"staffId"`
	Name    string `json:"name"`
	TxCount int64  `json:"txCount"`
	Revenue int64  `json:"revenue"`
}

func (q *Queries) ReportStaffPerformance(ctx context.Context, arg ReportStaffPerformanceParams) ([]ReportStaffPerformanceRow, error) {
	rows, err := q.db.QueryContext(ctx, reportStaffPerformance, arg.CreatedAt, arg.CreatedAt_2, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportStaffPerformanceRow{}
	for rows.Next() {
		var i ReportStaffPerformanceRow
		if err := rows.Scan(
			&i.StaffID,
			&i.Name,
			&i.TxCount,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportTopProducts = `-- name: ReportTopProducts :many
SELECT
  ti.product_name AS product_name,
  CAST(COALESCE(SUM(ti.quantity), 0) AS SIGNED) AS qty,
  CAST(COALESCE(SUM(ti.line_total), 0) AS SIGNED) AS revenue
FROM transaction_items ti
JOIN transactions t ON t.id = ti.transaction_id
WHERE t.store_id = ? AND t.status = 'completed' AND t.created_at >= ? AND t.created_at < ?
GROUP BY ti.product_name
ORDER BY qty DESC
LIMIT ?
`

type ReportTopProductsParams struct {
	StoreID     string    `json:"storeId"`
	CreatedAt   time.Time `json:"createdAt"`
	CreatedAt_2 time.Time `json:"createdAt2"`
	Limit       int32     `json:"limit"`
}

type ReportTopProductsRow struct {
	ProductName string `json:"productName"`
	Qty         int64  `json:"qty"`
	Revenue     int64  `json:"revenue"`
}

func (q *Queries) ReportTopProducts(ctx context.Context, arg ReportTopProductsParams) ([]ReportTopProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, reportTopProducts,
		arg.StoreID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportTopProductsRow{}
	for rows.Next() {
		var i ReportTopProductsRow
		if err := rows.Scan(&i.ProductName, &i.Qty, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
