// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: selforders.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :exec

INSERT INTO payments (id, store_id, self_order_id, provider, provider_ref, method, amount, status, raw_payload)
VALUES (?, ?, ?, ?, ?, 'qris', ?, ?, ?)
`

type CreatePaymentParams struct {
	ID          string           `json:"id"`
	StoreID     string           `json:"storeId"`
	SelfOrderID string           `json:"selfOrderId"`
	Provider    PaymentsProvider `json:"provider"`
	ProviderRef sql.NullString   `json:"providerRef"`
	Amount      int64            `json:"amount"`
	Status      PaymentsStatus   `json:"status"`
	RawPayload  sql.NullString   `json:"rawPayload"`
}

// Ledger pembayaran gateway (tabel `payments`) — dimiliki selforder (satu-satunya pemakai);
// module `payment` sendiri sudah tidak menyentuh tabel ini (lihat webhook_events.sql).
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.ID,
		arg.StoreID,
		arg.SelfOrderID,
		arg.Provider,
		arg.ProviderRef,
		arg.Amount,
		arg.Status,
		arg.RawPayload,
	)
	return err
}

const createSelfOrder = `-- name: CreateSelfOrder :exec
INSERT INTO self_orders (
  id, store_id, table_id, status, payment_method, payment_status, claim_code,
  subtotal, service_charge, gateway_fee, tax, total, customer_note, expires_at
) VALUES (?, ?, ?, 'placed', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSelfOrderParams struct {
	ID            string                  `json:"id"`
	StoreID       string                  `json:"storeId"`
	TableID       sql.NullString          `json:"tableId"`
	PaymentMethod SelfOrdersPaymentMethod `json:"paymentMethod"`
	PaymentStatus SelfOrdersPaymentStatus `json:"paymentStatus"`
	ClaimCode     sql.NullString          `json:"claimCode"`
	Subtotal      int64                   `json:"subtotal"`
	ServiceCharge int64                   `json:"serviceCharge"`
	GatewayFee    int64                   `json:"gatewayFee"`
	Tax           int64                   `json:"tax"`
	Total         int64                   `json:"total"`
	CustomerNote  sql.NullString          `json:"customerNote"`
	ExpiresAt     sql.NullTime            `json:"expiresAt"`
}

func (q *Queries) CreateSelfOrder(ctx context.Context, arg CreateSelfOrderParams) error {
	_, err := q.db.ExecContext(ctx, createSelfOrder,
		arg.ID,
		arg.StoreID,
		arg.TableID,
		arg.PaymentMethod,
		arg.PaymentStatus,
		arg.ClaimCode,
		arg.Subtotal,
		arg.ServiceCharge,
		arg.GatewayFee,
		arg.Tax,
		arg.Total,
		arg.CustomerNote,
		arg.ExpiresAt,
	)
	return err
}

const createSelfOrderItem = `-- name: CreateSelfOrderItem :exec
INSERT INTO self_order_items (
  id, self_order_id, product_id, product_name, category, price, quantity, line_total, note
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSelfOrderItemParams struct {
	ID          string         `json:"id"`
	SelfOrderID string         `json:"selfOrderId"`
	ProductID   sql.NullString `json:"productId"`
	ProductName string         `json:"productName"`
	Category    string         `json:"category"`
	Price       int64          `json:"price"`
	Quantity    int32          `json:"quantity"`
	LineTotal   int64          `json:"lineTotal"`
	Note        sql.NullString `json:"note"`
}

func (q *Queries) CreateSelfOrderItem(ctx context.Context, arg CreateSelfOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createSelfOrderItem,
		arg.ID,
		arg.SelfOrderID,
		arg.ProductID,
		arg.ProductName,
		arg.Category,
		arg.Price,
		arg.Quantity,
		arg.LineTotal,
		arg.Note,
	)
	return err
}

const expireOverdueSelfOrders = `-- name: ExpireOverdueSelfOrders :execrows
UPDATE self_orders SET payment_status = 'expired'
WHERE store_id = ? AND payment_status = 'pending' AND expires_at IS NOT NULL AND expires_at < ?
`

type ExpireOverdueSelfOrdersParams struct {
	StoreID   string       `json:"storeId"`
	ExpiresAt sql.NullTime `json:"expiresAt"`
}

func (q *Queries) ExpireOverdueSelfOrders(ctx context.Context, arg ExpireOverdueSelfOrdersParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireOverdueSelfOrders, arg.StoreID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPaymentBySelfOrder = `-- name: GetPaymentBySelfOrder :one
SELECT id, store_id, self_order_id, provider_ref, method, amount, status, raw_payload, created_at, updated_at, provider FROM payments WHERE self_order_id = ? ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetPaymentBySelfOrder(ctx context.Context, selfOrderID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentBySelfOrder, selfOrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SelfOrderID,
		&i.ProviderRef,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
	)
	return i, err
}

const getSelfOrder = `-- name: GetSelfOrder :one
SELECT id, store_id, table_id, status, payment_method, payment_status, claim_code, subtotal, total, customer_note, transaction_id, expires_at, created_at, updated_at, service_charge, gateway_fee, tax FROM self_orders WHERE id = ? AND store_id = ? LIMIT 1
`

type GetSelfOrderParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) GetSelfOrder(ctx context.Context, arg GetSelfOrderParams) (SelfOrder, error) {
	row := q.db.QueryRowContext(ctx, getSelfOrder, arg.ID, arg.StoreID)
	var i SelfOrder
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.TableID,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.ClaimCode,
		&i.Subtotal,
		&i.Total,
		&i.CustomerNote,
		&i.TransactionID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceCharge,
		&i.GatewayFee,
		&i.Tax,
	)
	return i, err
}

const getSelfOrderByClaimCode = `-- name: GetSelfOrderByClaimCode :one
SELECT id, store_id, table_id, status, payment_method, payment_status, claim_code, subtotal, total, customer_note, transaction_id, expires_at, created_at, updated_at, service_charge, gateway_fee, tax FROM self_orders WHERE store_id = ? AND claim_code = ? LIMIT 1
`

type GetSelfOrderByClaimCodeParams struct {
	StoreID   string         `json:"storeId"`
	ClaimCode sql.NullString `json:"claimCode"`
}

func (q *Queries) GetSelfOrderByClaimCode(ctx context.Context, arg GetSelfOrderByClaimCodeParams) (SelfOrder, error) {
	row := q.db.QueryRowContext(ctx, getSelfOrderByClaimCode, arg.StoreID, arg.ClaimCode)
	var i SelfOrder
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.TableID,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.ClaimCode,
		&i.Subtotal,
		&i.Total,
		&i.CustomerNote,
		&i.TransactionID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceCharge,
		&i.GatewayFee,
		&i.Tax,
	)
	return i, err
}

const getSelfOrderByID = `-- name: GetSelfOrderByID :one
SELECT id, store_id, table_id, status, payment_method, payment_status, claim_code, subtotal, total, customer_note, transaction_id, expires_at, created_at, updated_at, service_charge, gateway_fee, tax FROM self_orders WHERE id = ? LIMIT 1
`

func (q *Queries) GetSelfOrderByID(ctx context.Context, id string) (SelfOrder, error) {
	row := q.db.QueryRowContext(ctx, getSelfOrderByID, id)
	var i SelfOrder
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.TableID,
		&i.Status,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.ClaimCode,
		&i.Subtotal,
		&i.Total,
		&i.CustomerNote,
		&i.TransactionID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceCharge,
		&i.GatewayFee,
		&i.Tax,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT p.id, p.name, COALESCE(c.name, '') AS category, p.price, COALESCE(p.image_url, '') AS image_url
FROM products p LEFT JOIN product_categories c ON c.id = p.category_id
WHERE p.store_id = ? AND p.status = 'active'
ORDER BY c.sort_order ASC, p.name ASC
`

type ListActiveProductsRow struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Category string `json:"category"`
	Price    int64  `json:"price"`
	ImageUrl string `json:"imageUrl"`
}

func (q *Queries) ListActiveProducts(ctx context.Context, storeID string) ([]ListActiveProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProducts, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProductsRow{}
	for rows.Next() {
		var i ListActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Price,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelfOrderItems = `-- name: ListSelfOrderItems :many
SELECT id, self_order_id, product_id, product_name, category, price, quantity, line_total, note, created_at FROM self_order_items WHERE self_order_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListSelfOrderItems(ctx context.Context, selfOrderID string) ([]SelfOrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listSelfOrderItems, selfOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelfOrderItem{}
	for rows.Next() {
		var i SelfOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.SelfOrderID,
			&i.ProductID,
			&i.ProductName,
			&i.Category,
			&i.Price,
			&i.Quantity,
			&i.LineTotal,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSelfOrderPaid = `-- name: MarkSelfOrderPaid :exec
UPDATE self_orders SET payment_status = 'paid', transaction_id = ?, status = ? WHERE id = ?
`

type MarkSelfOrderPaidParams struct {
	TransactionID sql.NullString   `json:"transactionId"`
	Status        SelfOrdersStatus `json:"status"`
	ID            string           `json:"id"`
}

func (q *Queries) MarkSelfOrderPaid(ctx context.Context, arg MarkSelfOrderPaidParams) error {
	_, err := q.db.ExecContext(ctx, markSelfOrderPaid, arg.TransactionID, arg.Status, arg.ID)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET status = ?, raw_payload = ? WHERE id = ?
`

type UpdatePaymentStatusParams struct {
	Status     PaymentsStatus `json:"status"`
	RawPayload sql.NullString `json:"rawPayload"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus, arg.Status, arg.RawPayload, arg.ID)
	return err
}

const updateSelfOrderStatus = `-- name: UpdateSelfOrderStatus :execrows
UPDATE self_orders SET status = ? WHERE id = ? AND store_id = ?
`

type UpdateSelfOrderStatusParams struct {
	Status  SelfOrdersStatus `json:"status"`
	ID      string           `json:"id"`
	StoreID string           `json:"storeId"`
}

func (q *Queries) UpdateSelfOrderStatus(ctx context.Context, arg UpdateSelfOrderStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSelfOrderStatus, arg.Status, arg.ID, arg.StoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
