// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settings.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getSettingsByStore = `-- name: GetSettingsByStore :one

SELECT id, store_id, max_discount_percent, max_operational_expense, cash_variance_tolerance, feature_self_order, feature_qris, created_at, updated_at, tax_enabled, tax_percent, service_percent, feature_pay_at_cashier FROM settings WHERE store_id = ? LIMIT 1
`

// Tabel settings dimiliki modul `settings`. Pembaca lintas-modul memakai kontrak
// settingsclient; query di sini adalah satu-satunya akses tulis.
func (q *Queries) GetSettingsByStore(ctx context.Context, storeID string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingsByStore, storeID)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.MaxDiscountPercent,
		&i.MaxOperationalExpense,
		&i.CashVarianceTolerance,
		&i.FeatureSelfOrder,
		&i.FeatureQris,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaxEnabled,
		&i.TaxPercent,
		&i.ServicePercent,
		&i.FeaturePayAtCashier,
	)
	return i, err
}

const getStoreProfile = `-- name: GetStoreProfile :one

SELECT id, name, address, phone, logo_url FROM stores WHERE id = ? LIMIT 1
`

type GetStoreProfileRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Address sql.NullString `json:"address"`
	Phone   sql.NullString `json:"phone"`
	LogoUrl sql.NullString `json:"logoUrl"`
}

// stores adalah shared kernel; modul settings juga mengelola kolom profil (name/address/
// phone/logo_url) sebagai bagian dari "menu Pengaturan" — lihat knowledge/MODULE_MAP.md.
// Kolom lain di stores (type/timezone/currency) TIDAK disentuh dari sini.
func (q *Queries) GetStoreProfile(ctx context.Context, id string) (GetStoreProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getStoreProfile, id)
	var i GetStoreProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.LogoUrl,
	)
	return i, err
}

const updateStoreProfile = `-- name: UpdateStoreProfile :exec
UPDATE stores
SET name = ?, address = ?, phone = ?, logo_url = ?
WHERE id = ?
`

type UpdateStoreProfileParams struct {
	Name    string         `json:"name"`
	Address sql.NullString `json:"address"`
	Phone   sql.NullString `json:"phone"`
	LogoUrl sql.NullString `json:"logoUrl"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateStoreProfile(ctx context.Context, arg UpdateStoreProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateStoreProfile,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.LogoUrl,
		arg.ID,
	)
	return err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT INTO settings (
  id, store_id, max_discount_percent, max_operational_expense, cash_variance_tolerance,
  feature_self_order, feature_qris, feature_pay_at_cashier, tax_enabled, tax_percent, service_percent
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  max_discount_percent    = VALUES(max_discount_percent),
  max_operational_expense = VALUES(max_operational_expense),
  cash_variance_tolerance = VALUES(cash_variance_tolerance),
  feature_self_order      = VALUES(feature_self_order),
  feature_qris            = VALUES(feature_qris),
  feature_pay_at_cashier  = VALUES(feature_pay_at_cashier),
  tax_enabled             = VALUES(tax_enabled),
  tax_percent             = VALUES(tax_percent),
  service_percent         = VALUES(service_percent)
`

type UpsertSettingsParams struct {
	ID                    string `json:"id"`
	StoreID               string `json:"storeId"`
	MaxDiscountPercent    int32  `json:"maxDiscountPercent"`
	MaxOperationalExpense int64  `json:"maxOperationalExpense"`
	CashVarianceTolerance int64  `json:"cashVarianceTolerance"`
	FeatureSelfOrder      bool   `json:"featureSelfOrder"`
	FeatureQris           bool   `json:"featureQris"`
	FeaturePayAtCashier   bool   `json:"featurePayAtCashier"`
	TaxEnabled            bool   `json:"taxEnabled"`
	TaxPercent            int32  `json:"taxPercent"`
	ServicePercent        int32  `json:"servicePercent"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSettings,
		arg.ID,
		arg.StoreID,
		arg.MaxDiscountPercent,
		arg.MaxOperationalExpense,
		arg.CashVarianceTolerance,
		arg.FeatureSelfOrder,
		arg.FeatureQris,
		arg.FeaturePayAtCashier,
		arg.TaxEnabled,
		arg.TaxPercent,
		arg.ServicePercent,
	)
	return err
}
