// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settings.sql

package sqlcgen

import (
	"context"
)

const getSettingsByStore = `-- name: GetSettingsByStore :one

SELECT id, store_id, max_discount_percent, max_operational_expense, cash_variance_tolerance, feature_self_order, feature_qris, created_at, updated_at, tax_enabled, tax_percent, service_percent FROM settings WHERE store_id = ? LIMIT 1
`

// Tabel settings dimiliki modul `settings`. Pembaca lintas-modul memakai kontrak
// settingsclient; query di sini adalah satu-satunya akses tulis.
func (q *Queries) GetSettingsByStore(ctx context.Context, storeID string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingsByStore, storeID)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.MaxDiscountPercent,
		&i.MaxOperationalExpense,
		&i.CashVarianceTolerance,
		&i.FeatureSelfOrder,
		&i.FeatureQris,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaxEnabled,
		&i.TaxPercent,
		&i.ServicePercent,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT INTO settings (
  id, store_id, max_discount_percent, max_operational_expense, cash_variance_tolerance,
  feature_self_order, feature_qris, tax_enabled, tax_percent, service_percent
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  max_discount_percent    = VALUES(max_discount_percent),
  max_operational_expense = VALUES(max_operational_expense),
  cash_variance_tolerance = VALUES(cash_variance_tolerance),
  feature_self_order      = VALUES(feature_self_order),
  feature_qris            = VALUES(feature_qris),
  tax_enabled             = VALUES(tax_enabled),
  tax_percent             = VALUES(tax_percent),
  service_percent         = VALUES(service_percent)
`

type UpsertSettingsParams struct {
	ID                    string `json:"id"`
	StoreID               string `json:"storeId"`
	MaxDiscountPercent    int32  `json:"maxDiscountPercent"`
	MaxOperationalExpense int64  `json:"maxOperationalExpense"`
	CashVarianceTolerance int64  `json:"cashVarianceTolerance"`
	FeatureSelfOrder      bool   `json:"featureSelfOrder"`
	FeatureQris           bool   `json:"featureQris"`
	TaxEnabled            bool   `json:"taxEnabled"`
	TaxPercent            int32  `json:"taxPercent"`
	ServicePercent        int32  `json:"servicePercent"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSettings,
		arg.ID,
		arg.StoreID,
		arg.MaxDiscountPercent,
		arg.MaxOperationalExpense,
		arg.CashVarianceTolerance,
		arg.FeatureSelfOrder,
		arg.FeatureQris,
		arg.TaxEnabled,
		arg.TaxPercent,
		arg.ServicePercent,
	)
	return err
}
