// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: shifts.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const closeShift = `-- name: CloseShift :execrows
UPDATE shifts SET
  status = 'closed', cash_sales = ?, qris_sales = ?, additional_capital = ?,
  expenses = ?, withdrawals = ?, adjustments = ?, drawer_open_count = ?,
  expected_cash = ?, actual_cash = ?, variance = ?, close_approved_by = ?, closed_at = ?
WHERE id = ? AND store_id = ? AND status = 'open'
`

type CloseShiftParams struct {
	CashSales         int64          `json:"cashSales"`
	QrisSales         int64          `json:"qrisSales"`
	AdditionalCapital int64          `json:"additionalCapital"`
	Expenses          int64          `json:"expenses"`
	Withdrawals       int64          `json:"withdrawals"`
	Adjustments       int64          `json:"adjustments"`
	DrawerOpenCount   int32          `json:"drawerOpenCount"`
	ExpectedCash      sql.NullInt64  `json:"expectedCash"`
	ActualCash        sql.NullInt64  `json:"actualCash"`
	Variance          sql.NullInt64  `json:"variance"`
	CloseApprovedBy   sql.NullString `json:"closeApprovedBy"`
	ClosedAt          sql.NullTime   `json:"closedAt"`
	ID                string         `json:"id"`
	StoreID           string         `json:"storeId"`
}

func (q *Queries) CloseShift(ctx context.Context, arg CloseShiftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeShift,
		arg.CashSales,
		arg.QrisSales,
		arg.AdditionalCapital,
		arg.Expenses,
		arg.Withdrawals,
		arg.Adjustments,
		arg.DrawerOpenCount,
		arg.ExpectedCash,
		arg.ActualCash,
		arg.Variance,
		arg.CloseApprovedBy,
		arg.ClosedAt,
		arg.ID,
		arg.StoreID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countShifts = `-- name: CountShifts :one
SELECT COUNT(*) FROM shifts WHERE store_id = ?
`

func (q *Queries) CountShifts(ctx context.Context, storeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countShifts, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShift = `-- name: CreateShift :exec
INSERT INTO shifts (id, store_id, staff_id, status, initial_cash, opened_at)
VALUES (?, ?, ?, 'open', ?, ?)
`

type CreateShiftParams struct {
	ID          string    `json:"id"`
	StoreID     string    `json:"storeId"`
	StaffID     string    `json:"staffId"`
	InitialCash int64     `json:"initialCash"`
	OpenedAt    time.Time `json:"openedAt"`
}

func (q *Queries) CreateShift(ctx context.Context, arg CreateShiftParams) error {
	_, err := q.db.ExecContext(ctx, createShift,
		arg.ID,
		arg.StoreID,
		arg.StaffID,
		arg.InitialCash,
		arg.OpenedAt,
	)
	return err
}

const getOpenShift = `-- name: GetOpenShift :one
SELECT id, store_id, staff_id, status, initial_cash, cash_sales, qris_sales, additional_capital, expenses, withdrawals, adjustments, drawer_open_count, expected_cash, actual_cash, variance, close_approved_by, opened_at, closed_at, created_at, updated_at FROM shifts WHERE store_id = ? AND status = 'open' ORDER BY opened_at DESC LIMIT 1
`

func (q *Queries) GetOpenShift(ctx context.Context, storeID string) (Shift, error) {
	row := q.db.QueryRowContext(ctx, getOpenShift, storeID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.StaffID,
		&i.Status,
		&i.InitialCash,
		&i.CashSales,
		&i.QrisSales,
		&i.AdditionalCapital,
		&i.Expenses,
		&i.Withdrawals,
		&i.Adjustments,
		&i.DrawerOpenCount,
		&i.ExpectedCash,
		&i.ActualCash,
		&i.Variance,
		&i.CloseApprovedBy,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShift = `-- name: GetShift :one
SELECT id, store_id, staff_id, status, initial_cash, cash_sales, qris_sales, additional_capital, expenses, withdrawals, adjustments, drawer_open_count, expected_cash, actual_cash, variance, close_approved_by, opened_at, closed_at, created_at, updated_at FROM shifts WHERE id = ? AND store_id = ? LIMIT 1
`

type GetShiftParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) GetShift(ctx context.Context, arg GetShiftParams) (Shift, error) {
	row := q.db.QueryRowContext(ctx, getShift, arg.ID, arg.StoreID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.StaffID,
		&i.Status,
		&i.InitialCash,
		&i.CashSales,
		&i.QrisSales,
		&i.AdditionalCapital,
		&i.Expenses,
		&i.Withdrawals,
		&i.Adjustments,
		&i.DrawerOpenCount,
		&i.ExpectedCash,
		&i.ActualCash,
		&i.Variance,
		&i.CloseApprovedBy,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShifts = `-- name: ListShifts :many
SELECT id, store_id, staff_id, status, initial_cash, cash_sales, qris_sales, additional_capital, expenses, withdrawals, adjustments, drawer_open_count, expected_cash, actual_cash, variance, close_approved_by, opened_at, closed_at, created_at, updated_at FROM shifts WHERE store_id = ? ORDER BY opened_at DESC LIMIT ? OFFSET ?
`

type ListShiftsParams struct {
	StoreID string `json:"storeId"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListShifts(ctx context.Context, arg ListShiftsParams) ([]Shift, error) {
	rows, err := q.db.QueryContext(ctx, listShifts, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shift{}
	for rows.Next() {
		var i Shift
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.StaffID,
			&i.Status,
			&i.InitialCash,
			&i.CashSales,
			&i.QrisSales,
			&i.AdditionalCapital,
			&i.Expenses,
			&i.Withdrawals,
			&i.Adjustments,
			&i.DrawerOpenCount,
			&i.ExpectedCash,
			&i.ActualCash,
			&i.Variance,
			&i.CloseApprovedBy,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shiftCashMovementSummary = `-- name: ShiftCashMovementSummary :one
SELECT
  CAST(COALESCE(SUM(CASE WHEN type = 'capital' THEN amount END), 0) AS SIGNED) AS capital,
  CAST(COALESCE(SUM(CASE WHEN type = 'expense' THEN amount END), 0) AS SIGNED) AS expense,
  CAST(COALESCE(SUM(CASE WHEN type = 'adjustment' THEN amount END), 0) AS SIGNED) AS adjustment
FROM cash_movements WHERE shift_id = ?
`

type ShiftCashMovementSummaryRow struct {
	Capital    int64 `json:"capital"`
	Expense    int64 `json:"expense"`
	Adjustment int64 `json:"adjustment"`
}

func (q *Queries) ShiftCashMovementSummary(ctx context.Context, shiftID sql.NullString) (ShiftCashMovementSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, shiftCashMovementSummary, shiftID)
	var i ShiftCashMovementSummaryRow
	err := row.Scan(&i.Capital, &i.Expense, &i.Adjustment)
	return i, err
}

const shiftSalesSummary = `-- name: ShiftSalesSummary :one
SELECT
  CAST(COALESCE(SUM(CASE WHEN payment_method = 'cash' THEN total END), 0) AS SIGNED) AS cash_sales,
  CAST(COALESCE(SUM(CASE WHEN payment_method = 'qris' THEN total END), 0) AS SIGNED) AS qris_sales
FROM transactions WHERE shift_id = ? AND status = 'completed'
`

type ShiftSalesSummaryRow struct {
	CashSales int64 `json:"cashSales"`
	QrisSales int64 `json:"qrisSales"`
}

func (q *Queries) ShiftSalesSummary(ctx context.Context, shiftID sql.NullString) (ShiftSalesSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, shiftSalesSummary, shiftID)
	var i ShiftSalesSummaryRow
	err := row.Scan(&i.CashSales, &i.QrisSales)
	return i, err
}
