// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: staff.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createStaff = `-- name: CreateStaff :exec
INSERT INTO staff (id, store_id, name, username, email, password_hash, role, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateStaffParams struct {
	ID           string         `json:"id"`
	StoreID      string         `json:"storeId"`
	Name         string         `json:"name"`
	Username     string         `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"passwordHash"`
	Role         StaffRole      `json:"role"`
	Status       StaffStatus    `json:"status"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) error {
	_, err := q.db.ExecContext(ctx, createStaff,
		arg.ID,
		arg.StoreID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
	)
	return err
}

const deleteStaff = `-- name: DeleteStaff :exec
DELETE FROM staff WHERE id = ? AND store_id = ?
`

type DeleteStaffParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) DeleteStaff(ctx context.Context, arg DeleteStaffParams) error {
	_, err := q.db.ExecContext(ctx, deleteStaff, arg.ID, arg.StoreID)
	return err
}

const getStaffScoped = `-- name: GetStaffScoped :one
SELECT id, store_id, name, username, email, password_hash, role, status, created_at, updated_at FROM staff WHERE id = ? AND store_id = ? LIMIT 1
`

type GetStaffScopedParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) GetStaffScoped(ctx context.Context, arg GetStaffScopedParams) (Staff, error) {
	row := q.db.QueryRowContext(ctx, getStaffScoped, arg.ID, arg.StoreID)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaff = `-- name: ListStaff :many
SELECT id, store_id, name, username, email, password_hash, role, status, created_at, updated_at FROM staff WHERE store_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListStaff(ctx context.Context, storeID string) ([]Staff, error) {
	rows, err := q.db.QueryContext(ctx, listStaff, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaff = `-- name: UpdateStaff :exec
UPDATE staff SET name = ?, username = ?, email = ?, role = ?, status = ?
WHERE id = ? AND store_id = ?
`

type UpdateStaffParams struct {
	Name     string         `json:"name"`
	Username string         `json:"username"`
	Email    sql.NullString `json:"email"`
	Role     StaffRole      `json:"role"`
	Status   StaffStatus    `json:"status"`
	ID       string         `json:"id"`
	StoreID  string         `json:"storeId"`
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) error {
	_, err := q.db.ExecContext(ctx, updateStaff,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.Status,
		arg.ID,
		arg.StoreID,
	)
	return err
}

const updateStaffPassword = `-- name: UpdateStaffPassword :exec
UPDATE staff SET password_hash = ? WHERE id = ? AND store_id = ?
`

type UpdateStaffPasswordParams struct {
	PasswordHash string `json:"passwordHash"`
	ID           string `json:"id"`
	StoreID      string `json:"storeId"`
}

func (q *Queries) UpdateStaffPassword(ctx context.Context, arg UpdateStaffPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateStaffPassword, arg.PasswordHash, arg.ID, arg.StoreID)
	return err
}
