// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subscriptions.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countSubscriptionInvoices = `-- name: CountSubscriptionInvoices :one
SELECT COUNT(*) FROM subscription_invoices WHERE store_id = ?
`

func (q *Queries) CountSubscriptionInvoices(ctx context.Context, storeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscriptionInvoices, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscriptionInvoice = `-- name: CreateSubscriptionInvoice :exec
INSERT INTO subscription_invoices (id, store_id, plan_id, amount, status, provider, provider_ref)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSubscriptionInvoiceParams struct {
	ID          string                       `json:"id"`
	StoreID     string                       `json:"storeId"`
	PlanID      string                       `json:"planId"`
	Amount      int64                        `json:"amount"`
	Status      SubscriptionInvoicesStatus   `json:"status"`
	Provider    SubscriptionInvoicesProvider `json:"provider"`
	ProviderRef sql.NullString               `json:"providerRef"`
}

func (q *Queries) CreateSubscriptionInvoice(ctx context.Context, arg CreateSubscriptionInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, createSubscriptionInvoice,
		arg.ID,
		arg.StoreID,
		arg.PlanID,
		arg.Amount,
		arg.Status,
		arg.Provider,
		arg.ProviderRef,
	)
	return err
}

const createSubscriptionPlan = `-- name: CreateSubscriptionPlan :exec
INSERT INTO subscription_plans (id, code, name, price, period_days, is_active)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSubscriptionPlanParams struct {
	ID         string `json:"id"`
	Code       string `json:"code"`
	Name       string `json:"name"`
	Price      int64  `json:"price"`
	PeriodDays int32  `json:"periodDays"`
	IsActive   bool   `json:"isActive"`
}

func (q *Queries) CreateSubscriptionPlan(ctx context.Context, arg CreateSubscriptionPlanParams) error {
	_, err := q.db.ExecContext(ctx, createSubscriptionPlan,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Price,
		arg.PeriodDays,
		arg.IsActive,
	)
	return err
}

const getStoreSubscription = `-- name: GetStoreSubscription :one
SELECT id, store_id, plan_id, status, current_period_start, current_period_end, created_at, updated_at FROM store_subscriptions WHERE store_id = ? LIMIT 1
`

func (q *Queries) GetStoreSubscription(ctx context.Context, storeID string) (StoreSubscription, error) {
	row := q.db.QueryRowContext(ctx, getStoreSubscription, storeID)
	var i StoreSubscription
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionInvoice = `-- name: GetSubscriptionInvoice :one
SELECT id, store_id, plan_id, amount, status, provider, provider_ref, period_start, period_end, created_at, updated_at FROM subscription_invoices WHERE id = ? AND store_id = ? LIMIT 1
`

type GetSubscriptionInvoiceParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) GetSubscriptionInvoice(ctx context.Context, arg GetSubscriptionInvoiceParams) (SubscriptionInvoice, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionInvoice, arg.ID, arg.StoreID)
	var i SubscriptionInvoice
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.PlanID,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionInvoiceByID = `-- name: GetSubscriptionInvoiceByID :one
SELECT id, store_id, plan_id, amount, status, provider, provider_ref, period_start, period_end, created_at, updated_at FROM subscription_invoices WHERE id = ? LIMIT 1
`

func (q *Queries) GetSubscriptionInvoiceByID(ctx context.Context, id string) (SubscriptionInvoice, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionInvoiceByID, id)
	var i SubscriptionInvoice
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.PlanID,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionPlan = `-- name: GetSubscriptionPlan :one
SELECT id, code, name, price, period_days, is_active, renewal_only, created_at, updated_at FROM subscription_plans WHERE id = ? LIMIT 1
`

func (q *Queries) GetSubscriptionPlan(ctx context.Context, id string) (SubscriptionPlan, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionPlan, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Price,
		&i.PeriodDays,
		&i.IsActive,
		&i.RenewalOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSubscriptionPlans = `-- name: ListActiveSubscriptionPlans :many
SELECT id, code, name, price, period_days, is_active, renewal_only, created_at, updated_at FROM subscription_plans WHERE is_active = 1 ORDER BY price ASC
`

func (q *Queries) ListActiveSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscriptionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionPlan{}
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Price,
			&i.PeriodDays,
			&i.IsActive,
			&i.RenewalOnly,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSubscriptionPlans = `-- name: ListAllSubscriptionPlans :many
SELECT id, code, name, price, period_days, is_active, renewal_only, created_at, updated_at FROM subscription_plans ORDER BY price ASC
`

// Dipakai platform (superadmin) — termasuk plan nonaktif, tidak seperti ListActiveSubscriptionPlans.
func (q *Queries) ListAllSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.QueryContext(ctx, listAllSubscriptionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionPlan{}
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Price,
			&i.PeriodDays,
			&i.IsActive,
			&i.RenewalOnly,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionInvoices = `-- name: ListSubscriptionInvoices :many
SELECT id, store_id, plan_id, amount, status, provider, provider_ref, period_start, period_end, created_at, updated_at FROM subscription_invoices WHERE store_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListSubscriptionInvoicesParams struct {
	StoreID string `json:"storeId"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListSubscriptionInvoices(ctx context.Context, arg ListSubscriptionInvoicesParams) ([]SubscriptionInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionInvoices, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionInvoice{}
	for rows.Next() {
		var i SubscriptionInvoice
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.PlanID,
			&i.Amount,
			&i.Status,
			&i.Provider,
			&i.ProviderRef,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionInvoicePaid = `-- name: MarkSubscriptionInvoicePaid :execrows
UPDATE subscription_invoices SET status = 'paid', period_start = ?, period_end = ?
WHERE id = ? AND status = 'pending'
`

type MarkSubscriptionInvoicePaidParams struct {
	PeriodStart sql.NullTime `json:"periodStart"`
	PeriodEnd   sql.NullTime `json:"periodEnd"`
	ID          string       `json:"id"`
}

func (q *Queries) MarkSubscriptionInvoicePaid(ctx context.Context, arg MarkSubscriptionInvoicePaidParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSubscriptionInvoicePaid, arg.PeriodStart, arg.PeriodEnd, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sumPaidSubscriptionInvoices = `-- name: SumPaidSubscriptionInvoices :one
SELECT CAST(COALESCE(SUM(amount), 0) AS SIGNED) FROM subscription_invoices WHERE status = 'paid'
`

// Revenue platform (superadmin): total seluruh invoice LUNAS, LINTAS SEMUA TENANT — sengaja
// tanpa filter store_id, satu-satunya query di modul ini yang boleh begitu.
func (q *Queries) SumPaidSubscriptionInvoices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumPaidSubscriptionInvoices)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSubscriptionPlan = `-- name: UpdateSubscriptionPlan :execrows
UPDATE subscription_plans SET name = ?, price = ?, period_days = ?, is_active = ? WHERE id = ?
`

type UpdateSubscriptionPlanParams struct {
	Name       string `json:"name"`
	Price      int64  `json:"price"`
	PeriodDays int32  `json:"periodDays"`
	IsActive   bool   `json:"isActive"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSubscriptionPlan,
		arg.Name,
		arg.Price,
		arg.PeriodDays,
		arg.IsActive,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertStoreSubscriptionPeriod = `-- name: UpsertStoreSubscriptionPeriod :exec
INSERT INTO store_subscriptions (id, store_id, plan_id, status, current_period_start, current_period_end)
VALUES (?, ?, ?, 'active', ?, ?)
ON DUPLICATE KEY UPDATE
  plan_id = VALUES(plan_id),
  status = 'active',
  current_period_start = VALUES(current_period_start),
  current_period_end = VALUES(current_period_end)
`

type UpsertStoreSubscriptionPeriodParams struct {
	ID                 string       `json:"id"`
	StoreID            string       `json:"storeId"`
	PlanID             string       `json:"planId"`
	CurrentPeriodStart sql.NullTime `json:"currentPeriodStart"`
	CurrentPeriodEnd   sql.NullTime `json:"currentPeriodEnd"`
}

func (q *Queries) UpsertStoreSubscriptionPeriod(ctx context.Context, arg UpsertStoreSubscriptionPeriodParams) error {
	_, err := q.db.ExecContext(ctx, upsertStoreSubscriptionPeriod,
		arg.ID,
		arg.StoreID,
		arg.PlanID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	return err
}
