// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tables.sql

package sqlcgen

import (
	"context"
)

const createTable = `-- name: CreateTable :exec
INSERT INTO dining_tables (id, store_id, code, name, area, seats, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTableParams struct {
	ID      string             `json:"id"`
	StoreID string             `json:"storeId"`
	Code    string             `json:"code"`
	Name    string             `json:"name"`
	Area    string             `json:"area"`
	Seats   int32              `json:"seats"`
	Status  DiningTablesStatus `json:"status"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) error {
	_, err := q.db.ExecContext(ctx, createTable,
		arg.ID,
		arg.StoreID,
		arg.Code,
		arg.Name,
		arg.Area,
		arg.Seats,
		arg.Status,
	)
	return err
}

const deleteTable = `-- name: DeleteTable :exec
DELETE FROM dining_tables WHERE id = ? AND store_id = ?
`

type DeleteTableParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) DeleteTable(ctx context.Context, arg DeleteTableParams) error {
	_, err := q.db.ExecContext(ctx, deleteTable, arg.ID, arg.StoreID)
	return err
}

const getTable = `-- name: GetTable :one
SELECT id, store_id, code, name, area, seats, status, created_at, updated_at FROM dining_tables WHERE id = ? AND store_id = ? LIMIT 1
`

type GetTableParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) GetTable(ctx context.Context, arg GetTableParams) (DiningTable, error) {
	row := q.db.QueryRowContext(ctx, getTable, arg.ID, arg.StoreID)
	var i DiningTable
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Code,
		&i.Name,
		&i.Area,
		&i.Seats,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTableByCode = `-- name: GetTableByCode :one
SELECT id, store_id, code, name, area, seats, status, created_at, updated_at FROM dining_tables WHERE store_id = ? AND code = ? LIMIT 1
`

type GetTableByCodeParams struct {
	StoreID string `json:"storeId"`
	Code    string `json:"code"`
}

func (q *Queries) GetTableByCode(ctx context.Context, arg GetTableByCodeParams) (DiningTable, error) {
	row := q.db.QueryRowContext(ctx, getTableByCode, arg.StoreID, arg.Code)
	var i DiningTable
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Code,
		&i.Name,
		&i.Area,
		&i.Seats,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTables = `-- name: ListTables :many
SELECT id, store_id, code, name, area, seats, status, created_at, updated_at FROM dining_tables WHERE store_id = ? ORDER BY code ASC
`

func (q *Queries) ListTables(ctx context.Context, storeID string) ([]DiningTable, error) {
	rows, err := q.db.QueryContext(ctx, listTables, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiningTable{}
	for rows.Next() {
		var i DiningTable
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Code,
			&i.Name,
			&i.Area,
			&i.Seats,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTable = `-- name: UpdateTable :exec
UPDATE dining_tables SET code = ?, name = ?, area = ?, seats = ?, status = ?
WHERE id = ? AND store_id = ?
`

type UpdateTableParams struct {
	Code    string             `json:"code"`
	Name    string             `json:"name"`
	Area    string             `json:"area"`
	Seats   int32              `json:"seats"`
	Status  DiningTablesStatus `json:"status"`
	ID      string             `json:"id"`
	StoreID string             `json:"storeId"`
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) error {
	_, err := q.db.ExecContext(ctx, updateTable,
		arg.Code,
		arg.Name,
		arg.Area,
		arg.Seats,
		arg.Status,
		arg.ID,
		arg.StoreID,
	)
	return err
}
