// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :exec
INSERT INTO idempotency_keys (id, store_id, idempotency_key, request_hash, response_status, response_body)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateIdempotencyKeyParams struct {
	ID             string         `json:"id"`
	StoreID        string         `json:"storeId"`
	IdempotencyKey string         `json:"idempotencyKey"`
	RequestHash    string         `json:"requestHash"`
	ResponseStatus sql.NullInt32  `json:"responseStatus"`
	ResponseBody   sql.NullString `json:"responseBody"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error {
	_, err := q.db.ExecContext(ctx, createIdempotencyKey,
		arg.ID,
		arg.StoreID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (
  id, store_id, code, shift_id, table_id, self_order_id, cashier_id, order_type, source,
  payment_method, status, subtotal, discount, tax, service_charge, gateway_fee, total,
  amount_received, change_amount, discount_approved_by, customer_note, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTransactionParams struct {
	ID                 string                    `json:"id"`
	StoreID            string                    `json:"storeId"`
	Code               string                    `json:"code"`
	ShiftID            sql.NullString            `json:"shiftId"`
	TableID            sql.NullString            `json:"tableId"`
	SelfOrderID        sql.NullString            `json:"selfOrderId"`
	CashierID          sql.NullString            `json:"cashierId"`
	OrderType          TransactionsOrderType     `json:"orderType"`
	Source             TransactionsSource        `json:"source"`
	PaymentMethod      TransactionsPaymentMethod `json:"paymentMethod"`
	Status             TransactionsStatus        `json:"status"`
	Subtotal           int64                     `json:"subtotal"`
	Discount           int64                     `json:"discount"`
	Tax                int64                     `json:"tax"`
	ServiceCharge      int64                     `json:"serviceCharge"`
	GatewayFee         int64                     `json:"gatewayFee"`
	Total              int64                     `json:"total"`
	AmountReceived     int64                     `json:"amountReceived"`
	ChangeAmount       int64                     `json:"changeAmount"`
	DiscountApprovedBy sql.NullString            `json:"discountApprovedBy"`
	CustomerNote       sql.NullString            `json:"customerNote"`
	CreatedAt          time.Time                 `json:"createdAt"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.ID,
		arg.StoreID,
		arg.Code,
		arg.ShiftID,
		arg.TableID,
		arg.SelfOrderID,
		arg.CashierID,
		arg.OrderType,
		arg.Source,
		arg.PaymentMethod,
		arg.Status,
		arg.Subtotal,
		arg.Discount,
		arg.Tax,
		arg.ServiceCharge,
		arg.GatewayFee,
		arg.Total,
		arg.AmountReceived,
		arg.ChangeAmount,
		arg.DiscountApprovedBy,
		arg.CustomerNote,
		arg.CreatedAt,
	)
	return err
}

const createTransactionItem = `-- name: CreateTransactionItem :exec
INSERT INTO transaction_items (
  id, transaction_id, product_id, product_name, category, price, quantity, line_total, note
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTransactionItemParams struct {
	ID            string         `json:"id"`
	TransactionID string         `json:"transactionId"`
	ProductID     sql.NullString `json:"productId"`
	ProductName   string         `json:"productName"`
	Category      string         `json:"category"`
	Price         int64          `json:"price"`
	Quantity      int32          `json:"quantity"`
	LineTotal     int64          `json:"lineTotal"`
	Note          sql.NullString `json:"note"`
}

func (q *Queries) CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) error {
	_, err := q.db.ExecContext(ctx, createTransactionItem,
		arg.ID,
		arg.TransactionID,
		arg.ProductID,
		arg.ProductName,
		arg.Category,
		arg.Price,
		arg.Quantity,
		arg.LineTotal,
		arg.Note,
	)
	return err
}

const decrementStock = `-- name: DecrementStock :execrows
UPDATE products SET stock = stock - ?
WHERE id = ? AND store_id = ? AND stock >= ?
`

type DecrementStockParams struct {
	Qty     int32  `json:"qty"`
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

// Kurangi stok dengan penjaga stok >= qty (cegah stok negatif). 0 rows = gagal.
func (q *Queries) DecrementStock(ctx context.Context, arg DecrementStockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decrementStock,
		arg.Qty,
		arg.ID,
		arg.StoreID,
		arg.Qty,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, store_id, idempotency_key, request_hash, response_status, response_body, created_at FROM idempotency_keys WHERE store_id = ? AND idempotency_key = ? LIMIT 1
`

type GetIdempotencyKeyParams struct {
	StoreID        string `json:"storeId"`
	IdempotencyKey string `json:"idempotencyKey"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, arg.StoreID, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const getProductForSale = `-- name: GetProductForSale :one
SELECT p.id, p.name, COALESCE(c.name, '') AS category, p.price, p.status, p.stock
FROM products p LEFT JOIN product_categories c ON c.id = p.category_id
WHERE p.id = ? AND p.store_id = ? LIMIT 1
`

type GetProductForSaleParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

type GetProductForSaleRow struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Category string         `json:"category"`
	Price    int64          `json:"price"`
	Status   ProductsStatus `json:"status"`
	Stock    int32          `json:"stock"`
}

func (q *Queries) GetProductForSale(ctx context.Context, arg GetProductForSaleParams) (GetProductForSaleRow, error) {
	row := q.db.QueryRowContext(ctx, getProductForSale, arg.ID, arg.StoreID)
	var i GetProductForSaleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.Status,
		&i.Stock,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, store_id, code, shift_id, table_id, self_order_id, cashier_id, order_type, source, payment_method, status, subtotal, discount, tax, total, amount_received, change_amount, discount_approved_by, customer_note, created_at, service_charge, gateway_fee, voided_at, voided_by, void_reason FROM transactions WHERE id = ? AND store_id = ? LIMIT 1
`

type GetTransactionParams struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, arg.ID, arg.StoreID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Code,
		&i.ShiftID,
		&i.TableID,
		&i.SelfOrderID,
		&i.CashierID,
		&i.OrderType,
		&i.Source,
		&i.PaymentMethod,
		&i.Status,
		&i.Subtotal,
		&i.Discount,
		&i.Tax,
		&i.Total,
		&i.AmountReceived,
		&i.ChangeAmount,
		&i.DiscountApprovedBy,
		&i.CustomerNote,
		&i.CreatedAt,
		&i.ServiceCharge,
		&i.GatewayFee,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
	)
	return i, err
}

const listTransactionItems = `-- name: ListTransactionItems :many
SELECT id, transaction_id, product_id, product_name, category, price, quantity, line_total, note, created_at FROM transaction_items WHERE transaction_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListTransactionItems(ctx context.Context, transactionID string) ([]TransactionItem, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionItems, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionItem{}
	for rows.Next() {
		var i TransactionItem
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ProductID,
			&i.ProductName,
			&i.Category,
			&i.Price,
			&i.Quantity,
			&i.LineTotal,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumSelfOrderQrisRevenue = `-- name: SumSelfOrderQrisRevenue :one
SELECT CAST(COALESCE(SUM(total), 0) AS SIGNED) FROM transactions WHERE source = 'self_order' AND payment_method = 'qris' AND status = 'completed'
`

// Revenue platform (superadmin): GMV self-order YANG LEWAT QRIS SAJA (bukan cash-di-meja)
// LINTAS SEMUA TENANT — hanya QRIS yang settle ke rekening gateway bersama (PLAN.md §2.5),
// sengaja tanpa filter store_id, satu-satunya query di modul ini yang boleh begitu.
func (q *Queries) SumSelfOrderQrisRevenue(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumSelfOrderQrisRevenue)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumSelfOrderQrisRevenueByStore = `-- name: SumSelfOrderQrisRevenueByStore :one
SELECT CAST(COALESCE(SUM(total), 0) AS SIGNED) FROM transactions WHERE source = 'self_order' AND payment_method = 'qris' AND status = 'completed' AND store_id = ?
`

// Sama seperti SumSelfOrderQrisRevenue tapi utk satu tenant — basis AvailableBalance (§2.6).
func (q *Queries) SumSelfOrderQrisRevenueByStore(ctx context.Context, storeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumSelfOrderQrisRevenueByStore, storeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumSelfOrderQrisRevenueGroupedByStore = `-- name: SumSelfOrderQrisRevenueGroupedByStore :many
SELECT store_id, CAST(COALESCE(SUM(total), 0) AS SIGNED) AS total
FROM transactions WHERE source = 'self_order' AND payment_method = 'qris' AND status = 'completed'
GROUP BY store_id
`

type SumSelfOrderQrisRevenueGroupedByStoreRow struct {
	StoreID string `json:"storeId"`
	Total   int64  `json:"total"`
}

// Sama seperti SumSelfOrderQrisRevenue tapi per-tenant sekaligus (Revenue Tenant page, §2.6).
func (q *Queries) SumSelfOrderQrisRevenueGroupedByStore(ctx context.Context) ([]SumSelfOrderQrisRevenueGroupedByStoreRow, error) {
	rows, err := q.db.QueryContext(ctx, sumSelfOrderQrisRevenueGroupedByStore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumSelfOrderQrisRevenueGroupedByStoreRow{}
	for rows.Next() {
		var i SumSelfOrderQrisRevenueGroupedByStoreRow
		if err := rows.Scan(&i.StoreID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voidTransaction = `-- name: VoidTransaction :execrows
UPDATE transactions
SET status = 'voided', voided_at = ?, voided_by = ?,
    void_reason = ?
WHERE id = ? AND store_id = ? AND status = 'completed'
`

type VoidTransactionParams struct {
	VoidedAt   sql.NullTime   `json:"voidedAt"`
	VoidedBy   sql.NullString `json:"voidedBy"`
	VoidReason sql.NullString `json:"voidReason"`
	ID         string         `json:"id"`
	StoreID    string         `json:"storeId"`
}

// Batalkan transaksi (void). Hanya transaksi 'completed' yang bisa dibatalkan; 0 rows =
// tidak ditemukan / sudah dibatalkan. Pengecualian (tunai, dalam shift) ditegakkan di service.
func (q *Queries) VoidTransaction(ctx context.Context, arg VoidTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, voidTransaction,
		arg.VoidedAt,
		arg.VoidedBy,
		arg.VoidReason,
		arg.ID,
		arg.StoreID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
