// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: webhook_events.sql

package sqlcgen

import (
	"context"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :exec
INSERT INTO webhook_events (id, provider, event_id) VALUES (?, ?, ?)
`

type CreateWebhookEventParams struct {
	ID       string `json:"id"`
	Provider string `json:"provider"`
	EventID  string `json:"eventId"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) error {
	_, err := q.db.ExecContext(ctx, createWebhookEvent, arg.ID, arg.Provider, arg.EventID)
	return err
}

const getWebhookEvent = `-- name: GetWebhookEvent :one
SELECT id, provider, event_id, processed_at, created_at FROM webhook_events WHERE provider = ? AND event_id = ? LIMIT 1
`

type GetWebhookEventParams struct {
	Provider string `json:"provider"`
	EventID  string `json:"eventId"`
}

func (q *Queries) GetWebhookEvent(ctx context.Context, arg GetWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEvent, arg.Provider, arg.EventID)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventID,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}
