// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: withdrawals.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countWithdrawals = `-- name: CountWithdrawals :one
SELECT COUNT(*) FROM withdrawals WHERE store_id = ?
`

func (q *Queries) CountWithdrawals(ctx context.Context, storeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWithdrawals, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWithdrawal = `-- name: CreateWithdrawal :exec
INSERT INTO withdrawals (id, store_id, amount, bank, account, holder, status, reference, requested_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWithdrawalParams struct {
	ID          string            `json:"id"`
	StoreID     string            `json:"storeId"`
	Amount      int64             `json:"amount"`
	Bank        string            `json:"bank"`
	Account     string            `json:"account"`
	Holder      string            `json:"holder"`
	Status      WithdrawalsStatus `json:"status"`
	Reference   sql.NullString    `json:"reference"`
	RequestedBy sql.NullString    `json:"requestedBy"`
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) error {
	_, err := q.db.ExecContext(ctx, createWithdrawal,
		arg.ID,
		arg.StoreID,
		arg.Amount,
		arg.Bank,
		arg.Account,
		arg.Holder,
		arg.Status,
		arg.Reference,
		arg.RequestedBy,
	)
	return err
}

const listWithdrawals = `-- name: ListWithdrawals :many
SELECT id, store_id, amount, bank, account, holder, status, reference, requested_by, created_at, updated_at FROM withdrawals WHERE store_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListWithdrawalsParams struct {
	StoreID string `json:"storeId"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListWithdrawals(ctx context.Context, arg ListWithdrawalsParams) ([]Withdrawal, error) {
	rows, err := q.db.QueryContext(ctx, listWithdrawals, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Withdrawal{}
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Amount,
			&i.Bank,
			&i.Account,
			&i.Holder,
			&i.Status,
			&i.Reference,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
