-- Fase 2 — operasional: shift, transaksi (+item snapshot), mutasi kas, penarikan.

CREATE TABLE shifts (
  id                  CHAR(26) NOT NULL,
  store_id            CHAR(26) NOT NULL,
  staff_id            CHAR(26) NOT NULL,
  status              ENUM('open','closed') NOT NULL DEFAULT 'open',
  initial_cash        BIGINT   NOT NULL DEFAULT 0,
  cash_sales          BIGINT   NOT NULL DEFAULT 0,
  qris_sales          BIGINT   NOT NULL DEFAULT 0,
  additional_capital  BIGINT   NOT NULL DEFAULT 0,
  expenses            BIGINT   NOT NULL DEFAULT 0,
  withdrawals         BIGINT   NOT NULL DEFAULT 0,
  adjustments         BIGINT   NOT NULL DEFAULT 0,
  drawer_open_count   INT      NOT NULL DEFAULT 0,
  expected_cash       BIGINT   NULL,
  actual_cash         BIGINT   NULL,
  variance            BIGINT   NULL,
  close_approved_by   CHAR(26) NULL,
  opened_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at           DATETIME NULL,
  created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_shifts_store_status (store_id, status),
  KEY idx_shifts_staff (staff_id),
  CONSTRAINT fk_shifts_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
  CONSTRAINT fk_shifts_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
  CONSTRAINT fk_shifts_approver FOREIGN KEY (close_approved_by) REFERENCES staff (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE transactions (
  id                    CHAR(26)    NOT NULL,
  store_id              CHAR(26)    NOT NULL,
  code                  VARCHAR(40) NOT NULL,
  shift_id              CHAR(26)    NULL,
  table_id              CHAR(26)    NULL,
  self_order_id         CHAR(26)    NULL,
  cashier_id            CHAR(26)    NULL,
  order_type            ENUM('dineIn','takeaway') NOT NULL DEFAULT 'takeaway',
  source                ENUM('cashier','self_order') NOT NULL DEFAULT 'cashier',
  payment_method        ENUM('cash','qris') NOT NULL DEFAULT 'cash',
  status                ENUM('completed','voided','refunded') NOT NULL DEFAULT 'completed',
  subtotal              BIGINT      NOT NULL DEFAULT 0,
  discount              BIGINT      NOT NULL DEFAULT 0,
  tax                   BIGINT      NOT NULL DEFAULT 0,
  total                 BIGINT      NOT NULL DEFAULT 0,
  amount_received       BIGINT      NOT NULL DEFAULT 0,
  change_amount         BIGINT      NOT NULL DEFAULT 0,
  discount_approved_by  CHAR(26)    NULL,
  customer_note         VARCHAR(255) NULL,
  created_at            DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_transactions_store_code (store_id, code),
  KEY idx_transactions_store_created (store_id, created_at),
  KEY idx_transactions_shift (shift_id),
  KEY idx_transactions_source (source),
  KEY idx_transactions_status (status),
  KEY idx_transactions_cashier (cashier_id),
  KEY idx_transactions_self_order (self_order_id),
  CONSTRAINT fk_transactions_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
  CONSTRAINT fk_transactions_shift FOREIGN KEY (shift_id) REFERENCES shifts (id),
  CONSTRAINT fk_transactions_table FOREIGN KEY (table_id) REFERENCES dining_tables (id),
  CONSTRAINT fk_transactions_cashier FOREIGN KEY (cashier_id) REFERENCES staff (id),
  CONSTRAINT fk_transactions_discount_approver FOREIGN KEY (discount_approved_by) REFERENCES staff (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Snapshot item — kebal terhadap edit produk berikutnya.
CREATE TABLE transaction_items (
  id              CHAR(26)     NOT NULL,
  transaction_id  CHAR(26)     NOT NULL,
  product_id      CHAR(26)     NULL,
  product_name    VARCHAR(150) NOT NULL,
  category        VARCHAR(120) NOT NULL DEFAULT '',
  price           BIGINT       NOT NULL DEFAULT 0,
  quantity        INT          NOT NULL DEFAULT 0,
  line_total      BIGINT       NOT NULL DEFAULT 0,
  note            VARCHAR(255) NULL,
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_transaction_items_tx (transaction_id),
  CONSTRAINT fk_transaction_items_tx FOREIGN KEY (transaction_id) REFERENCES transactions (id) ON DELETE CASCADE,
  CONSTRAINT fk_transaction_items_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cash_movements (
  id           CHAR(26)     NOT NULL,
  store_id     CHAR(26)     NOT NULL,
  shift_id     CHAR(26)     NULL,
  type         ENUM('capital','expense','adjustment') NOT NULL,
  amount       BIGINT       NOT NULL DEFAULT 0,
  notes        VARCHAR(255) NULL,
  created_by   CHAR(26)     NULL,
  approved_by  CHAR(26)     NULL,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_cash_movements_shift (shift_id),
  KEY idx_cash_movements_store_created (store_id, created_at),
  CONSTRAINT fk_cash_movements_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
  CONSTRAINT fk_cash_movements_shift FOREIGN KEY (shift_id) REFERENCES shifts (id),
  CONSTRAINT fk_cash_movements_creator FOREIGN KEY (created_by) REFERENCES staff (id),
  CONSTRAINT fk_cash_movements_approver FOREIGN KEY (approved_by) REFERENCES staff (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE withdrawals (
  id            CHAR(26)     NOT NULL,
  store_id      CHAR(26)     NOT NULL,
  amount        BIGINT       NOT NULL DEFAULT 0,
  bank          VARCHAR(80)  NOT NULL DEFAULT '',
  account       VARCHAR(60)  NOT NULL DEFAULT '',
  holder        VARCHAR(120) NOT NULL DEFAULT '',
  status        ENUM('pending','processing','success','failed') NOT NULL DEFAULT 'pending',
  reference     VARCHAR(100) NULL,
  requested_by  CHAR(26)     NULL,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_withdrawals_store_created (store_id, created_at),
  CONSTRAINT fk_withdrawals_store FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
  CONSTRAINT fk_withdrawals_requester FOREIGN KEY (requested_by) REFERENCES admin_users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
