// Central registry of API paths (relative to VITE_API_BASE_URL, e.g. /api/v1).
// Modules reference these instead of hardcoding strings.
export const endpoints = {
  auth: {
    adminLogin: "/auth/admin/login",
    staffLogin: "/auth/staff/login",
    platformLogin: "/auth/platform/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    me: "/auth/me",
  },
  products: "/products",
  categories: "/categories",
  tables: "/tables",
  staff: "/staff",
  adminUsers: "/admin-users",
  transactions: "/transactions",
  shifts: "/shifts",
  cashMovements: "/cash-movements",
  withdrawals: "/withdrawals",
  withdrawalBalance: "/withdrawals/balance",
  reports: {
    dashboard: "/reports/dashboard",
    sales: "/reports/sales",
    topProducts: "/reports/top-products",
    salesByCategory: "/reports/sales-by-category",
    paymentDistribution: "/reports/payment-distribution",
    staffPerformance: "/reports/staff-performance",
  },
  selfOrders: "/self-orders",
  publicOrder: "/public/order",
  uploads: "/uploads",
  settings: "/settings",
  subscription: {
    root: "/subscription",
    plans: "/subscription/plans",
    checkout: "/subscription/checkout",
    invoices: "/subscription/invoices",
  },
  platform: {
    tenants: "/platform/tenants",
    tenantsRevenue: "/platform/tenants/revenue",
    revenue: "/platform/revenue",
    plans: "/platform/plans",
    withdrawals: "/platform/withdrawals",
    withdrawalHistory: "/platform/withdrawals/history",
    users: "/platform/users",
    paymentConfig: "/platform/payment-config",
    paymentClients: "/platform/payment-clients",
  },
} as const;
